// Mapping rules for Anu Script 7 (Anu 7) Legacy Telugu Font Encoding
import type { MappingEntry } from './anu6';

export const ANU7_UNICODE_TO_NONUNICODE: MappingEntry[] = [
  // Multi-character conjuncts & complex gunintalu (Matched first)
  { from: "క్షం", to: "™¥" },
  { from: "క్షా", to: "™Á" },
  { from: "క్షి", to: "™Â" },
  { from: "క్షీ", to: "™Ã" },
  { from: "క్షు", to: "™Ä" },
  { from: "క్షూ", to: "™Å" },
  { from: "క్షె", to: "™È" },
  { from: "క్షే", to: "™É" },
  { from: "క్షై", to: "™Ê" },
  { from: "క్షొ", to: "™Ë" },
  { from: "క్షో", to: "™Ì" },
  { from: "క్షౌ", to: "™Í" },
  { from: "క్ష", to: "™" },
  { from: "జ్ఞ", to: "ˆ" },
  { from: "త్ర", to: "à" },
  { from: "శ్రీ", to: "Ò°" },
  { from: "శ్రి", to: "Ò" },
  { from: "శ్ర", to: "Ò" },

  // Base Vowels (Achulu)
  { from: "అ", to: "A" },
  { from: "ఆ", to: "B" },
  { from: "ఇ", to: "C" },
  { from: "ఈ", to: "D" },
  { from: "ఉ", to: "E" },
  { from: "ఊ", to: "F" },
  { from: "ఋ", to: "G" },
  { from: "ౠ", to: "H" },
  { from: "ఎ", to: "I" },
  { from: "ఏ", to: "J" },
  { from: "ఐ", to: "K" },
  { from: "ఒ", to: "L" },
  { from: "ఓ", to: "M" },
  { from: "ఔ", to: "N" },
  { from: "అం", to: "A¥" },
  { from: "అః", to: "A¦" },

  // Base Consonants (Hallulu)
  { from: "క", to: "a" },
  { from: "ఖ", to: "b" },
  { from: "గ", to: "c" },
  { from: "ఘ", to: "d" },
  { from: "ఙ", to: "e" },
  { from: "చ", to: "f" },
  { from: "ఛ", to: "g" },
  { from: "జ", to: "h" },
  { from: "ఝ", to: "i" },
  { from: "ఞ", to: "j" },
  { from: "ట", to: "k" },
  { from: "ఠ", to: "l" },
  { from: "డ", to: "m" },
  { from: "ఢ", to: "n" },
  { from: "ణ", to: "o" },
  { from: "త", to: "p" },
  { from: "థ", to: "q" },
  { from: "ద", to: "r" },
  { from: "ధ", to: "s" },
  { from: "న", to: "t" },
  { from: "ప", to: "u" },
  { from: "ఫ", to: "v" },
  { from: "బ", to: "w" },
  { from: "భ", to: "x" },
  { from: "మ", to: "y" },
  { from: "య", to: "z" },
  { from: "ర", to: "`" },
  { from: "ల", to: "{" },
  { from: "వ", to: "|" },
  { from: "శ", to: "}" },
  { from: "ష", to: "~" },
  { from: "స", to: "!" },
  { from: "హ", to: "@" },
  { from: "ళ", to: "#" },
  { from: "ఱ", to: "$" },

  // Vowel Signs / Gunintalu (Matras)
  { from: "ా", to: "Á" },
  { from: "ి", to: "Â" },
  { from: "ీ", to: "Ã" },
  { from: "ు", to: "Ä" },
  { from: "ూ", to: "Å" },
  { from: "ృ", to: "Æ" },
  { from: "ౄ", to: "Ç" },
  { from: "ె", to: "È" },
  { from: "ే", to: "É" },
  { from: "ై", to: "Ê" },
  { from: "ొ", to: "Ë" },
  { from: "ో", to: "Ì" },
  { from: "ౌ", to: "Í" },
  { from: "్", to: "Î" },
  { from: "ం", to: "¥" },
  { from: "ః", to: "¦" },

  // Subscript / Vattu Signs
  { from: "్క", to: "™" },
  { from: "్ఖ", to: "š" },
  { from: "్గ", to: "›" },
  { from: "్ఘ", to: "œ" },
  { from: "్చ", to: "ž" },
  { from: "్ఛ", to: "Ÿ" },
  { from: "్జ", to: " " },
  { from: "్ఝ", to: "¡" },
  { from: "్ట", to: "¢" },
  { from: "్ఠ", to: "£" },
  { from: "్డ", to: "¤" },
  { from: "్ఢ", to: "¥" },
  { from: "్ణ", to: "¦" },
  { from: "్త", to: "§" },
  { from: "్థ", to: "¨" },
  { from: "్ద", to: "©" },
  { from: "్ధ", to: "ª" },
  { from: "్న", to: "«" },
  { from: "్ప", to: "¬" },
  { from: "్ఫ", to: "®" },
  { from: "్బ", to: "¯" },
  { from: "్భ", to: "°" },
  { from: "్మ", to: "±" },
  { from: "్య", to: "²" },
  { from: "్ర", to: "³" },
  { from: "్ల", to: "´" },
  { from: "్వ", to: "µ" },
  { from: "్శ", to: "¶" },
  { from: "్ష", to: "·" },
  { from: "్స", to: "¸" },
  { from: "్హ", to: "¹" },
  { from: "్ళ", to: "º" },

  // Numerals
  { from: "౦", to: "0" },
  { from: "౧", to: "1" },
  { from: "౨", to: "2" },
  { from: "౩", to: "3" },
  { from: "౪", to: "4" },
  { from: "౫", to: "5" },
  { from: "౬", to: "6" },
  { from: "౭", to: "7" },
  { from: "౮", to: "8" },
  { from: "౯", to: "9" }
];
