/**
 * Complete Unicode to Anu Script / Legacy Tamil Mapping
 * Supports:
 * - All Independent Vowels (உயிர் எழுத்துக்கள்)
 * - Aytham (ஆய்த எழுத்து)
 * - All Pure Consonants with Virama/Pulli (மெய் எழுத்துக்கள்)
 * - All 216 Uyirmei Combinations (உயிர்மெய் எழுத்துக்கள்)
 * - All Grantha Consonants (கிரந்த எழுத்துக்கள்): ஜ, ஷ, ஸ, ஹ, க்ஷ, ஶ, ஸ்ரீ
 * - Pre-base vowel signs (ெ, ே, ை)
 * - Split vowel signs (ொ, ோ, ௌ)
 * - Numerals and Punctuation
 */

export interface MappingEntry {
  from: string;
  to: string;
}

export const ANU_TAMIL_UNICODE_TO_NONUNICODE: MappingEntry[] = [
  // Punctuation & Special
  { from: ",", to: ">" },
  { from: "ஸ்ரீ", to: "=" },
  { from: "ஃ", to: "/" },

  // --- Grantha: Ksha (க்ஷ) combinations ---
  { from: "க்ஷௌ", to: "f;n\\s" },
  { from: "க்ஷோ", to: "f;N\\h" },
  { from: "க்ஷொ", to: "f;n\\h" },
  { from: "க்ஷா", to: "f;\\h" },
  { from: "க்ஷி", to: "f;\\p" },
  { from: "க்ஷீ", to: "f;\\P" },
  { from: "க்ஷு", to: "f;\\{" },
  { from: "க்ஷூ", to: "f;\\_" },
  { from: "க்ஷெ", to: "f;n\\" },
  { from: "க்ஷே", to: "f;N\\" },
  { from: "க்ஷை", to: "f;i\\" },
  { from: "க்ஷ்", to: "f;\\;" },
  { from: "க்ஷ", to: "f;\\" },

  // --- Grantha: Ja (ஜ) combinations ---
  { from: "ஜௌ", to: "n[s" },
  { from: "ஜோ", to: "N[h" },
  { from: "ஜொ", to: "n[h" },
  { from: "ஜா", to: "[h" },
  { from: "ஜி", to: "[p" },
  { from: "ஜீ", to: "[P" },
  { from: "ஜு", to: "[{" },
  { from: "ஜூ", to: "[_" },
  { from: "ஜெ", to: "n[" },
  { from: "ஜே", to: "N[" },
  { from: "ஜை", to: "i[" },
  { from: "ஜ்", to: "[;" },
  { from: "ஜ", to: "[" },

  // --- Grantha: Sha (ஷ) combinations ---
  { from: "ஷௌ", to: "n\\s" },
  { from: "ஷோ", to: "N\\h" },
  { from: "ஷொ", to: "n\\h" },
  { from: "ஷா", to: "\\h" },
  { from: "ஷி", to: "\\p" },
  { from: "ஷீ", to: "\\P" },
  { from: "ஷு", to: "\\{" },
  { from: "ஷூ", to: "\\_" },
  { from: "ஷெ", to: "n\\" },
  { from: "ஷே", to: "N\\" },
  { from: "ஷை", to: "i\\" },
  { from: "ஷ்", to: "\\;" },
  { from: "ஷ", to: "\\" },

  // --- Grantha: Sa (ஸ) combinations ---
  { from: "ஸௌ", to: "n]s" },
  { from: "ஸோ", to: "N]h" },
  { from: "ஸொ", to: "n]h" },
  { from: "ஸா", to: "]h" },
  { from: "ஸி", to: "]p" },
  { from: "ஸீ", to: "]P" },
  { from: "ஸு", to: "]{" },
  { from: "ஸூ", to: "]_" },
  { from: "ஸெ", to: "n]" },
  { from: "ஸே", to: "N]" },
  { from: "ஸை", to: "i]" },
  { from: "ஸ்", to: "];" },
  { from: "ஸ", to: "]" },

  // --- Grantha: Ha (ஹ) combinations ---
  { from: "ஹௌ", to: "n`s" },
  { from: "ஹோ", to: "N`h" },
  { from: "ஹொ", to: "n`h" },
  { from: "ஹா", to: "`h" },
  { from: "ஹி", to: "`p" },
  { from: "ஹீ", to: "`P" },
  { from: "ஹு", to: "`{" },
  { from: "ஹூ", to: "`_" },
  { from: "ஹெ", to: "n`" },
  { from: "ஹே", to: "N`" },
  { from: "ஹை", to: "i`" },
  { from: "ஹ்", to: "`;" },
  { from: "ஹ", to: "`" },

  // --- Grantha: Ssha (ஶ) combinations ---
  { from: "ஶௌ", to: "n]rs" },
  { from: "ஶோ", to: "N]rh" },
  { from: "ஶொ", to: "n]rh" },
  { from: "ஶா", to: "]rh" },
  { from: "ஶி", to: "]rp" },
  { from: "ஶீ", to: "]rP" },
  { from: "ஶு", to: "]r{" },
  { from: "ஶூ", to: "]r_" },
  { from: "ஶெ", to: "n]r" },
  { from: "ஶே", to: "N]r" },
  { from: "ஶை", to: "i]r" },
  { from: "ஶ்", to: "]r;" },
  { from: "ஶ", to: "]r" },

  // --- Consonant: Ka (க) combinations ---
  { from: "கௌ", to: "nfs" },
  { from: "கோ", to: "Nfh" },
  { from: "கொ", to: "nfh" },
  { from: "கா", to: "fh" },
  { from: "கி", to: "fp" },
  { from: "கீ", to: "fP" },
  { from: "கு", to: "F" },
  { from: "கூ", to: "$" },
  { from: "கெ", to: "nf" },
  { from: "கே", to: "Nf" },
  { from: "கை", to: "if" },
  { from: "க்", to: "f;" },
  { from: "க", to: "f" },

  // --- Consonant: Nga (ங) combinations ---
  { from: "ஙௌ", to: "nqs" },
  { from: "ஙோ", to: "Nqh" },
  { from: "ஙொ", to: "nqh" },
  { from: "ஙா", to: "qh" },
  { from: "ஙி", to: "qp" },
  { from: "ஙீ", to: "qP" },
  { from: "ஙு", to: "q{" },
  { from: "ஙூ", to: "q_" },
  { from: "ஙெ", to: "nq" },
  { from: "ஙே", to: "Nq" },
  { from: "ஙை", to: "iq" },
  { from: "ங்", to: "q;" },
  { from: "ங", to: "q" },

  // --- Consonant: Ca/Sa (ச) combinations ---
  { from: "சௌ", to: "nrs" },
  { from: "சோ", to: "Nrh" },
  { from: "சொ", to: "nrh" },
  { from: "சா", to: "rh" },
  { from: "சி", to: "rp" },
  { from: "சீ", to: "rP" },
  { from: "சு", to: "R" },
  { from: "சூ", to: "R+" },
  { from: "செ", to: "nr" },
  { from: "சே", to: "Nr" },
  { from: "சை", to: "ir" },
  { from: "ச்", to: "r;" },
  { from: "ச", to: "r" },

  // --- Consonant: Nya (ஞ) combinations ---
  { from: "ஞௌ", to: "nQs" },
  { from: "ஞோ", to: "NQh" },
  { from: "ஞொ", to: "nQh" },
  { from: "ஞா", to: "Qh" },
  { from: "ஞி", to: "Qp" },
  { from: "ஞீ", to: "QP" },
  { from: "ஞு", to: "Q{" },
  { from: "ஞூ", to: "Q_" },
  { from: "ஞெ", to: "nQ" },
  { from: "ஞே", to: "NQ" },
  { from: "ஞை", to: "iQ" },
  { from: "ஞ்", to: "Q;" },
  { from: "ஞ", to: "Q" },

  // --- Consonant: Tta/Da (ட) combinations ---
  { from: "டௌ", to: "nls" },
  { from: "டோ", to: "Nlh" },
  { from: "டொ", to: "nlh" },
  { from: "டா", to: "lh" },
  { from: "டி", to: "b" },
  { from: "டீ", to: "B" },
  { from: "டு", to: "L" },
  { from: "டூ", to: "^" },
  { from: "டெ", to: "nl" },
  { from: "டே", to: "Nl" },
  { from: "டை", to: "il" },
  { from: "ட்", to: "l;" },
  { from: "ட", to: "l" },

  // --- Consonant: Nna (ண) combinations ---
  { from: "ணௌ", to: "nzs" },
  { from: "ணோ", to: "Nzh" },
  { from: "ணொ", to: "nzh" },
  { from: "ணா", to: "zh" },
  { from: "ணி", to: "zp" },
  { from: "ணீ", to: "zP" },
  { from: "ணு", to: "Z" },
  { from: "ணூ", to: "Z}" },
  { from: "ணெ", to: "nz" },
  { from: "ணே", to: "Nz" },
  { from: "ணை", to: "iz" },
  { from: "ண்", to: "z;" },
  { from: "ண", to: "z" },

  // --- Consonant: Ta/Tha (த) combinations ---
  { from: "தௌ", to: "njs" },
  { from: "தோ", to: "Njh" },
  { from: "தொ", to: "njh" },
  { from: "தா", to: "jh" },
  { from: "தி", to: "jp" },
  { from: "தீ", to: "jP" },
  { from: "து", to: "J" },
  { from: "தூ", to: "J}" },
  { from: "தெ", to: "nj" },
  { from: "தே", to: "Nj" },
  { from: "தை", to: "ij" },
  { from: "த்", to: "j;" },
  { from: "த", to: "j" },

  // --- Consonant: Na (ந) combinations ---
  { from: "நௌ", to: "nes" },
  { from: "நோ", to: "Neh" },
  { from: "நொ", to: "neh" },
  { from: "நா", to: "eh" },
  { from: "நி", to: "ep" },
  { from: "நீ", to: "eP" },
  { from: "நு", to: "E" },
  { from: "நூ", to: "E}" },
  { from: "நெ", to: "ne" },
  { from: "நே", to: "Ne" },
  { from: "நை", to: "ie" },
  { from: "ந்", to: "e;" },
  { from: "ந", to: "e" },

  // --- Consonant: Nna2 (ன) combinations ---
  { from: "னௌ", to: "nds" },
  { from: "னோ", to: "Ndh" },
  { from: "னொ", to: "ndh" },
  { from: "னா", to: "dh" },
  { from: "னி", to: "dp" },
  { from: "னீ", to: "dP" },
  { from: "னு", to: "D" },
  { from: "னூ", to: "D}" },
  { from: "னெ", to: "nd" },
  { from: "னே", to: "Nd" },
  { from: "னை", to: "id" },
  { from: "ன்", to: "d;" },
  { from: "ன", to: "d" },

  // --- Consonant: Pa (ப) combinations ---
  { from: "பௌ", to: "ngs" },
  { from: "போ", to: "Ngh" },
  { from: "பொ", to: "ngh" },
  { from: "பா", to: "gh" },
  { from: "பி", to: "gp" },
  { from: "பீ", to: "gP" },
  { from: "பு", to: "G" },
  { from: "பூ", to: "G+" },
  { from: "பெ", to: "ng" },
  { from: "பே", to: "Ng" },
  { from: "பை", to: "ig" },
  { from: "ப்", to: "g;" },
  { from: "ப", to: "g" },

  // --- Consonant: Ma (ம) combinations ---
  { from: "மௌ", to: "nks" },
  { from: "மோ", to: "Nkh" },
  { from: "மொ", to: "nkh" },
  { from: "மா", to: "kh" },
  { from: "மி", to: "kp" },
  { from: "மீ", to: "kP" },
  { from: "மு", to: "K" },
  { from: "மூ", to: "%" },
  { from: "மெ", to: "nk" },
  { from: "மே", to: "Nk" },
  { from: "மை", to: "ik" },
  { from: "ம்", to: "k;" },
  { from: "ம", to: "k" },

  // --- Consonant: Ya (ய) combinations ---
  { from: "யௌ", to: "nas" },
  { from: "யோ", to: "Nah" },
  { from: "யொ", to: "nah" },
  { from: "யா", to: "ah" },
  { from: "யி", to: "ap" },
  { from: "யீ", to: "aP" },
  { from: "யு", to: "A" },
  { from: "யூ", to: "A+" },
  { from: "யெ", to: "na" },
  { from: "யே", to: "Na" },
  { from: "யை", to: "ia" },
  { from: "ய்", to: "a;" },
  { from: "ய", to: "a" },

  // --- Consonant: Ra (ர) combinations ---
  { from: "ரௌ", to: "nus" },
  { from: "ரோ", to: "Nuh" },
  { from: "ரொ", to: "nuh" },
  { from: "ரா", to: "uh" },
  { from: "ரி", to: "up" },
  { from: "ரீ", to: "uP" },
  { from: "ரு", to: "U" },
  { from: "ரூ", to: "&" },
  { from: "ரெ", to: "nu" },
  { from: "ரே", to: "Nu" },
  { from: "ரை", to: "iu" },
  { from: "ர்", to: "u;" },
  { from: "ர", to: "u" },

  // --- Consonant: La (ல) combinations ---
  { from: "லௌ", to: "nys" },
  { from: "லோ", to: "Nyh" },
  { from: "லொ", to: "nyh" },
  { from: "லா", to: "yh" },
  { from: "லி", to: "yp" },
  { from: "லீ", to: "yP" },
  { from: "லு", to: "Y" },
  { from: "லூ", to: "Y}" },
  { from: "லெ", to: "ny" },
  { from: "லே", to: "Ny" },
  { from: "லை", to: "iy" },
  { from: "ல்", to: "y;" },
  { from: "ல", to: "y" },

  // --- Consonant: Lla (ள) combinations ---
  { from: "ளௌ", to: "nss" },
  { from: "ளோ", to: "Nsh" },
  { from: "ளொ", to: "nsh" },
  { from: "ளா", to: "sh" },
  { from: "ளி", to: "sp" },
  { from: "ளீ", to: "sP" },
  { from: "ளு", to: "S" },
  { from: "ளூ", to: "Sh" },
  { from: "ளெ", to: "ns" },
  { from: "ளே", to: "Ns" },
  { from: "ளை", to: "is" },
  { from: "ள்", to: "s;" },
  { from: "ள", to: "s" },

  // --- Consonant: Va (வ) combinations ---
  { from: "வௌ", to: "nts" },
  { from: "வோ", to: "Nth" },
  { from: "வொ", to: "nth" },
  { from: "வா", to: "th" },
  { from: "வி", to: "tp" },
  { from: "வீ", to: "tP" },
  { from: "வு", to: "T" },
  { from: "வூ", to: "T+" },
  { from: "வெ", to: "nt" },
  { from: "வே", to: "Nt" },
  { from: "வை", to: "it" },
  { from: "வ்", to: "t;" },
  { from: "வ", to: "t" },

  // --- Consonant: Zha (ழ) combinations ---
  { from: "ழௌ", to: "nos" },
  { from: "ழோ", to: "Noh" },
  { from: "ழொ", to: "noh" },
  { from: "ழா", to: "oh" },
  { from: "ழி", to: "op" },
  { from: "ழீ", to: "oP" },
  { from: "ழு", to: "O" },
  { from: "ழூ", to: "O}" },
  { from: "ழெ", to: "no" },
  { from: "ழே", to: "No" },
  { from: "ழை", to: "io" },
  { from: "ழ்", to: "o;" },
  { from: "ழ", to: "o" },

  // --- Consonant: Rra (ற) combinations ---
  { from: "றௌ", to: "nws" },
  { from: "றோ", to: "Nwh" },
  { from: "றொ", to: "nwh" },
  { from: "றா", to: "wh" },
  { from: "றி", to: "wp" },
  { from: "றீ", to: "wP" },
  { from: "று", to: "W" },
  { from: "றூ", to: "W}" },
  { from: "றெ", to: "nw" },
  { from: "றே", to: "Nw" },
  { from: "றை", to: "iw" },
  { from: "ற்", to: "w;" },
  { from: "ற", to: "w" },

  // --- Independent Vowels (உயிர் எழுத்துக்கள்) ---
  { from: "அ", to: "m" },
  { from: "ஆ", to: "M" },
  { from: "இ", to: "," },
  { from: "ஈ", to: "<" },
  { from: "உ", to: "c" },
  { from: "ஊ", to: "C" },
  { from: "எ", to: "v" },
  { from: "ஏ", to: "V" },
  { from: "ஐ", to: "I" },
  { from: "ஒ", to: "x" },
  { from: "ஓ", to: "X" },
  { from: "ஔ", to: "xs" },

  // Standalone Matras & Modifiers
  { from: "ா", to: "h" },
  { from: "ி", to: "p" },
  { from: "ீ", to: "P" },
  { from: "ு", to: "{" },
  { from: "ூ", to: "_" },
  { from: "ெ", to: "n" },
  { from: "ே", to: "N" },
  { from: "ை", to: "i" },
  { from: "ொ", to: "nh" },
  { from: "ோ", to: "Nh" },
  { from: "்", to: ";" }
];
