// Mapping rules for Apple Telugu / Modular Legacy Font Encoding
import type { MappingEntry } from './anu6';

export const APPLE_TELUGU_UNICODE_TO_NONUNICODE: MappingEntry[] = [
  { from: "క్షం", to: "qx" },
  { from: "క్షా", to: "qa" },
  { from: "క్షి", to: "qi" },
  { from: "క్షీ", to: "qI" },
  { from: "క్షు", to: "qu" },
  { from: "క్షూ", to: "qU" },
  { from: "క్ష", to: "q" },
  { from: "జ్ఞ", to: "j~" },
  { from: "త్ర", to: "tr" },
  { from: "శ్రీ", to: "SrI" },
  { from: "శ్ర", to: "Sr" },

  // Base Vowels
  { from: "అ", to: "a" },
  { from: "ఆ", to: "aa" },
  { from: "ఇ", to: "i" },
  { from: "ఈ", to: "ii" },
  { from: "ఉ", to: "u" },
  { from: "ఊ", to: "uu" },
  { from: "ఋ", to: "ru" },
  { from: "ఎ", to: "e" },
  { from: "ఏ", to: "ee" },
  { from: "ఐ", to: "ai" },
  { from: "ఒ", to: "o" },
  { from: "ఓ", to: "oo" },
  { from: "ఔ", to: "au" },

  // Consonants
  { from: "క", to: "k" },
  { from: "ఖ", to: "kh" },
  { from: "గ", to: "g" },
  { from: "ఘ", to: "gh" },
  { from: "చ", to: "ch" },
  { from: "ఛ", to: "Ch" },
  { from: "జ", to: "j" },
  { from: "ఝ", to: "jh" },
  { from: "ట", to: "T" },
  { from: "ఠ", to: "Th" },
  { from: "డ", to: "D" },
  { from: "ఢ", to: "Dh" },
  { from: "ణ", to: "N" },
  { from: "త", to: "t" },
  { from: "థ", to: "th" },
  { from: "ద", to: "d" },
  { from: "ధ", to: "dh" },
  { from: "న", to: "n" },
  { from: "ప", to: "p" },
  { from: "ఫ", to: "ph" },
  { from: "బ", to: "b" },
  { from: "భ", to: "bh" },
  { from: "మ", to: "m" },
  { from: "య", to: "y" },
  { from: "ర", to: "r" },
  { from: "ల", to: "l" },
  { from: "వ", to: "v" },
  { from: "శ", to: "S" },
  { from: "ష", to: "Sh" },
  { from: "స", to: "s" },
  { from: "హ", to: "h" },
  { from: "ళ", to: "L" },

  // Matras
  { from: "ా", to: "A" },
  { from: "ి", to: "i" },
  { from: "ీ", to: "I" },
  { from: "ు", to: "u" },
  { from: "ూ", to: "U" },
  { from: "ృ", to: "R" },
  { from: "ె", to: "E" },
  { from: "ే", to: "EE" },
  { from: "ై", to: "AI" },
  { from: "ొ", to: "O" },
  { from: "ో", to: "OO" },
  { from: "ౌ", to: "AU" },
  { from: "ం", to: "M" },
  { from: "ః", to: "H" }
];
