// Bamini Legacy Tamil Font Mapping
export const BAMINI_TAMIL_UNICODE_TO_NONUNICODE = [
  // Vowels
  { from: "அ", to: "m" },
  { from: "ஆ", to: "M" },
  { from: "இ", to: "E" },
  { from: "ஈ", to: "FF" },
  { from: "உ", to: "c" },
  { from: "ஊ", to: "C" },
  { from: "எ", to: "v" },
  { from: "ஏ", to: "V" },
  { from: "ஐ", to: "I" },
  { from: "ஒ", to: "x" },
  { from: "ஓ", to: "X" },
  { from: "ஔ", to: "xs" },
  { from: "ஃ", to: "F" },

  // Grantha consonants
  { from: "ஶ்ரீ", to: "ஸ்ரீ" },
  { from: "ஸ்ரீ", to: "SRI" },
  { from: "ஜ", to: "j" },
  { from: "ஷ", to: "S" },
  { from: "ஸ", to: "s" },
  { from: "ஹ", to: "h" },
  { from: "க்ஷ", to: "K" },

  // Consonants
  { from: "க", to: "f" },
  { from: "ங", to: "q" },
  { from: "ச", to: "r" },
  { from: "ஞ", to: "n" },
  { from: "ட", to: "l" },
  { from: "ண", to: "z" },
  { from: "த", to: "j" },
  { from: "ந", to: "w" },
  { from: "ன", to: "d" },
  { from: "ப", to: "g" },
  { from: "ம", to: "k" },
  { from: "ய", to: "a" },
  { from: "ர", to: "u" },
  { from: "ల", to: "y" },
  { from: "ல", to: "y" },
  { from: "வ", to: "t" },
  { from: "ழ", to: "o" },
  { from: "ள", to: "s" },
  { from: "ற", to: "R" },

  // Vowel Signs
  { from: "ா", to: "h" },
  { from: "ி", to: "p" },
  { from: "ீ", to: "P" },
  { from: "ு", to: "u" },
  { from: "ூ", to: "U" },
  { from: "ெ", to: "e" },
  { from: "ே", to: "E" },
  { from: "ை", to: "i" },
  { from: "ொ", to: "eh" },
  { from: "ோ", to: "Eh" },
  { from: "ௌ", to: "es" },
  { from: "்", to: ";" }
];
