export const HARI_GUJARATI_MAPPINGS = [
  // Numbers
  { from: '૦', to: '0' },
  { from: '૧', to: '1' },
  { from: '૨', to: '2' },
  { from: '૩', to: '3' },
  { from: '૪', to: '4' },
  { from: '૫', to: '5' },
  { from: '૬', to: '6' },
  { from: '૭', to: '7' },
  { from: '૮', to: '8' },
  { from: '૯', to: '9' },

  // Special Conjuncts & Ligatures MUST come before half letters
  { from: 'સ્ત્ર', to: 'à' },
  { from: 'ક્ય', to: '±y' },
  { from: 'ક્ક', to: 'Ê' },
  { from: 'ત્ર', to: '#i' },
  { from: 'ક્ષ', to: 'x' },
  { from: 'જ્ઞ', to: 'X' },
  { from: 'દ્ય', to: 'w' },
  { from: 'દ્વ', to: 'o' },
  { from: 'દ્દ', to: 'Ñ' },
  { from: 'દ્ધ', to: 'Ü' },
  { from: 'દ્મ', to: 'Þ' },
  { from: 'શ્ર', to: '~' },
  { from: 'ટ્ર', to: 'T^' },
  { from: 'ડ્ર', to: 'D^' },
  { from: 'દ્ર', to: 'W' },
  { from: 'પ્ર', to: 'p\\' },
  { from: 'ક્ર', to: 'k|' },
  { from: 'રુ', to: '@' },
  { from: 'રૂ', to: '$' },
  { from: 'શ્વ', to: 'V' },     

  // Half Consonants
  { from: 'જ્', to: '¶' },
  { from: 'સ્', to: 'A' },
  { from: 'શ્', to: 'V' },     
  { from: 'ખ્', to: '²' },
  { from: 'વ્', to: 'Ä' },
  { from: 'ક્', to: 'k`' },
  { from: 'થ્', to: '¸' },
  { from: 'ચ્', to: '´' },
  { from: 'બ્', to: 'º' },
  { from: 'મ્', to: 'µ' },
  { from: 'લ્', to: '½' },
  { from: 'ધ્', to: '¼' },
  { from: 'ણ્', to: '»' },
  { from: 'પ્', to: '¿' },
  { from: 'ભ્', to: 'Á' },

  // Base Vowels
  { from: 'અ', to: 'a' },
  { from: 'આ', to: 'ai' },
  { from: 'ઇ', to: 'e' },
  { from: 'ઈ', to: 'E' },
  { from: 'ઉ', to: 'u' },
  { from: 'ઊ', to: 'U' },
  { from: 'ઋ', to: 'ä' },
  { from: 'એ', to: 'a[' },
  { from: 'ઐ', to: 'a]' },
  { from: 'ઓ', to: 'ai[' },
  { from: 'ઔ', to: 'ai]' },

  // Dependent Vowels (Matras)
  { from: 'ા', to: 'i' },
  { from: 'ી', to: ')' },
  { from: 'ુ', to: '&' },
  { from: 'ૂ', to: '*' },
  { from: 'ૃ', to: 'Z' },
  { from: 'ે', to: '[' },
  { from: 'ૈ', to: ']' },
  { from: 'ો', to: 'i[' },
  { from: 'ૌ', to: 'i]' },
  { from: 'ં', to: '>' },
  { from: 'ઃ', to: ':' },

  // Consonants
  { from: 'ક', to: 'k' },
  { from: 'ખ', to: 'K' },
  { from: 'ગ', to: 'g' },
  { from: 'ઘ', to: 'G' },
  { from: 'ઙ', to: 'ઙ' },
  { from: 'ચ', to: 'c' },
  { from: 'છ', to: 'C' },
  { from: 'જ', to: 'j' },
  { from: 'ઝ', to: 'z' },
  { from: 'ઞ', to: 'ઞ' },
  { from: 'ટ', to: 'T' },
  { from: 'ઠ', to: 'q' },
  { from: 'ડ', to: 'D' },
  { from: 'ઢ', to: 'Q' },
  { from: 'ણ', to: 'N' },
  { from: 'ત', to: 't' },
  { from: 'થ', to: 'Y' },
  { from: 'દ', to: 'd' },
  { from: 'ધ', to: 'F' },
  { from: 'ન', to: 'n' },
  { from: 'પ', to: 'p' },
  { from: 'ફ', to: 'f' },
  { from: 'બ', to: 'b' },
  { from: 'ભ', to: 'B' },
  { from: 'મ', to: 'm' },
  { from: 'ય', to: 'y' },
  { from: 'ર', to: 'r' },
  { from: 'લ', to: 'l' },
  { from: 'વ', to: 'v' },
  { from: 'શ', to: 'S' },
  { from: 'ષ', to: 'P' },
  { from: 'સ', to: 's' },
  { from: 'હ', to: 'h' },
  { from: 'ળ', to: 'L' },

  // Default Halant
  { from: '્', to: '`' }
];
