// ISM / Revathi Legacy Malayalam Font Mapping
export const ISM_MALAYALAM_UNICODE_TO_NONUNICODE = [
  // Vowels
  { from: "അ", to: "A" },
  { from: "ആ", to: "B" },
  { from: "ഇ", to: "C" },
  { from: "ഈ", to: "D" },
  { from: "ഉ", to: "E" },
  { from: "ഊ", to: "F" },
  { from: "ഋ", to: "G" },
  { from: "എ", to: "H" },
  { from: "ഏ", to: "I" },
  { from: "ഐ", to: "J" },
  { from: "ഒ", to: "K" },
  { from: "ഓ", to: "L" },
  { from: "ഔ", to: "M" },
  { from: "അം", to: "An" },
  { from: "അഃ", to: "Ah" },

  // Consonants
  { from: "ക", to: "k" },
  { from: "ഖ", to: "kh" },
  { from: "ഗ", to: "g" },
  { from: "ഘ", to: "gh" },
  { from: "ങ", to: "ng" },
  { from: "ച", to: "ch" },
  { from: "ഛ", to: "Ch" },
  { from: "ജ", to: "j" },
  { from: "ഝ", to: "jh" },
  { from: "ഞ", to: "nj" },
  { from: "ട", to: "t" },
  { from: "ഠ", to: "th" },
  { from: "ഡ", to: "d" },
  { from: "ഢ", to: "dh" },
  { from: "ണ", to: "n" },
  { from: "ത", to: "th" },
  { from: "ഥ", to: "Th" },
  { from: "ദ", to: "d" },
  { from: "ധ", to: "dh" },
  { from: "ന", to: "na" },
  { from: "പ", to: "p" },
  { from: "ഫ", to: "ph" },
  { from: "ബ", to: "b" },
  { from: "ഭ", to: "bh" },
  { from: "മ", to: "m" },
  { from: "യ", to: "y" },
  { from: "ര", to: "r" },
  { from: "ല", to: "l" },
  { from: "വ", to: "v" },
  { from: "ശ", to: "sh" },
  { from: "ഷ", to: "Sh" },
  { from: "സ", to: "s" },
  { from: "ഹ", to: "h" },
  { from: "ള", to: "L" },
  { from: "ഴ", to: "zh" },
  { from: "റ", to: "R" },

  // Vowel Signs
  { from: "ാ", to: "aa" },
  { from: "ി", to: "i" },
  { from: "ീ", to: "ee" },
  { from: "ു", to: "u" },
  { from: "ൂ", to: "oo" },
  { from: "ൃ", to: "r" },
  { from: "െ", to: "e" },
  { from: "േ", to: "E" },
  { from: "ൈ", to: "ai" },
  { from: "ൊ", to: "o" },
  { from: "ോ", to: "O" },
  { from: "ൌ", to: "au" },
  { from: "ൗ", to: "au" },
  { from: "്", to: "്" }
];
