// Mapping rules for Kruti Dev 010 / Devlys 010 (Hindi Legacy Font Encoding)
import type { MappingEntry } from './anu6';

export const KRUTI_DEV_UNICODE_TO_NONUNICODE: MappingEntry[] = [
  // Special Conjuncts & Matras
  { from: "क्र", to: "d" },
  { from: "ज्ञ", to: "T" },
  { from: "त्र", to: "=" },
  { from: "क्ष", to: "Õ" },
  { from: "श्र", to: "J" },
  { from: "द्ध", to: "ö" },
  { from: "द्व", to: "n" },
  { from: "द्य", to: "|" },
  { from: "ट्ट", to: "ê" },
  { from: "ट्ठ", to: "ë" },

  // Base Vowels
  { from: "अ", to: "v" },
  { from: "आ", to: "vk" },
  { from: "इ", to: "b" },
  { from: "ई", to: "bZ" },
  { from: "उ", to: "m" },
  { from: "ऊ", to: "mW" },
  { from: "ऋ", to: "Í" },
  { from: "ए", to: "s" },
  { from: "ऐ", to: "sW" },
  { from: "ओ", to: "vks" },
  { from: "औ", to: "vkS" },

  // Consonants
  { from: "क", to: "d" },
  { from: "ख", to: "K" },
  { from: "ग", to: "x" },
  { from: "घ", to: "Ä" },
  { from: "ङ", to: "Ã" },
  { from: "च", to: "p" },
  { from: "छ", to: "N" },
  { from: "ज", to: "t" },
  { from: "झ", to: "Í" },
  { from: "ञ", to: "¥" },
  { from: "ट", to: "V" },
  { from: "ठ", to: "B" },
  { from: "ड", to: "M" },
  { from: "ढ", to: "<" },
  { from: "ण", to: "f.k" },
  { from: "त", to: "r" },
  { from: "थ", to: "Fk" },
  { from: "द", to: "n" },
  { from: "ध", to: "èk" },
  { from: "न", to: "u" },
  { from: "प", to: "i" },
  { from: "फ", to: "Q" },
  { from: "ब", to: "c" },
  { from: "भ", to: "Hk" },
  { from: "म", to: "e" },
  { from: "य", to: "e" },
  { from: "र", to: "j" },
  { from: "ल", to: "y" },
  { from: "व", to: "o" },
  { from: "श", to: "r" },
  { from: "ष", to: "ष" },
  { from: "स", to: "ls" },
  { from: "ह", to: "g" },

  // Matras
  { from: "ा", to: "k" },
  { from: "ि", to: "f" },
  { from: "ी", to: "Z" },
  { from: "ु", to: "q" },
  { from: "ू", to: "w" },
  { from: "ृ", to: "`" },
  { from: "े", to: "s" },
  { from: "ै", to: "S" },
  { from: "ो", to: "ks" },
  { from: "ौ", to: "kS" },
  { from: "ं", to: "a" },
  { from: "ः", to: "%" },
  { from: "्", to: "્" }
];
