// GENERATED by scratch/telugu0908/build_tables.py - do not edit by hand.
//
// Encoding: Shree-Tel-0908 (Modular Infotech, 2001), addressed through the font's (3,1)
// Unicode cmap - the one both Chromium and Windows resolve text through. Every value below
// is a string of those cmap characters. The font's glyph names are standard Macintosh names
// assigned by position and carry no meaning, so nothing here was read off a name.
//
// The in-page preview needs the sanitised face (public/SHREE-TEL-web.ttf): Chromium's
// OpenType Sanitiser rejects the original outright ("post: Bad string index 5") and falls
// back to a Latin font without saying so.
//
// Provenance for every value: scratch/telugu0908/INVENTORY.md.

/** Free-standing marks. */
export const ANUSVARA = '\u2026';
export const VISARGA = '@';
export const POLLU = '\u0152';
export const NAKAARA_POLLU = '\u201C';
export const REPH = '\u201D';
export const AI_LENGTH = '\u2022';
export const TA_RA = '\u02C6';

export interface ConsonantForms {
  /** Standalone letter, talakattu included where the letter takes one. */
  full: string;
  /** Form used when a vowel sign or a subscript follows; the sign takes the talakattu's place. */
  base: string;
  /** Subscript (vattu) form, emitted after a virama. */
  vattu: string;
  /** Single glyph covering base + vowel sign, where the font provides one. Cannot carry an
   *  intervening subscript, so it is used only when the cluster has none. */
  pre?: Record<string, string>;
  /** Per-consonant spelling of each vowel sign: which width variant, and whether the sign is
   *  written as one mark or two. Measured per pair - a single variant per sign is what made
   *  the earlier tables render ై ొ ో ౌ wrongly. */
  mark: Record<string, string>;
  /** Signs that follow `full` rather than `base`: the ones drawn below the letter, which
   *  leave its talakattu alone. */
  onFull?: string[];
  /** Advance-only glyph emitted between this letter and a following subscript. A subscript is
   *  a mark whose ink sits at about x -450..-60, so it needs the pen roughly 450 units in to
   *  land under the letter; a narrow letter plus its talakattu only reaches ~220 and the mark
   *  would be drawn beside it instead. Absent for letters already wide enough. */
  pad?: string;
  /** Which of the three width-matched pollu marks sits over this letter. */
  pollu: string;
  /** Subscripts whose own x range needs a different pad from this letter's default, keyed by
   *  the following consonant. The marks span x -599..-21, so one pad cannot centre all of
   *  them; an empty string means no pad at all. */
  padFor?: Record<string, string>;
}

export const CONSONANTS: Record<string, ConsonantForms> = {
  'క': { full: 'M\u00E6', base: 'M', vattu: 'O', pollu: '\u0160', pad: '\u00FF', padFor: { 'క': '\u00FC', 'గ': '\u00FD', 'ఘ': '\u00FE', 'ఝ': '\u00FD', 'ఞ': '\u00FE', 'ట': '\u00FE', 'ఠ': '\u00FC', 'డ': '\u00FE', 'ఢ': '\u00FE', 'త': '\u00FC', 'థ': '\u00FE', 'ద': '\u00FE', 'ధ': '\u00FE', 'ర': '\u00FE', 'ష': '\u00FE', 'హ': '\u00FC', 'క్ష': '\u00FE' }, onFull: ['ు', 'ూ', 'ృ', 'ె', 'ే', 'ై'], mark: { 'ా': '>', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '#', 'ౄ': '#*', 'ె': '\u00F0', 'ే': '\u00F3', 'ై': '\u00F0\u2022', 'ొ': '\u0178', 'ో': '\u00F8', 'ౌ': 'o' } },
  'ఖ': { full: 'Q', base: 'R', vattu: 'U', pollu: '\u0160', onFull: ['ు', 'ూ', 'ృ', 'ౄ'], pre: { 'ి': 'S', 'ీ': 'T' }, mark: { 'ా': '\u00EA', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '\u2013', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F4', 'ై': '\u00F1\u2022', 'ొ': '\u0178', 'ో': 'Z', 'ౌ': 'o' } },
  'గ': { full: 'V\u00E6', base: 'V', vattu: 'Y', pollu: '\u0160', pad: '\u00FF', padFor: { 'క': '\u00FC', 'ఖ': '\u00FD', 'గ': '\u00FC', 'ఘ': '\u00FE', 'ఝ': '\u00FC', 'ఞ': '\u00FE', 'ట': '\u00FE', 'ఠ': '\u00FC', 'డ': '\u00FE', 'ఢ': '\u00FE', 'త': '\u00FC', 'థ': '\u00FE', 'ద': '\u00FE', 'ధ': '\u00FE', 'ర': '\u00FE', 'ష': '\u00FE', 'హ': '', 'క్ష': '\u00FE' }, onFull: ['ి', 'ీ', 'ు', 'ూ', 'ౄ'], pre: { 'ి': 'W', 'ీ': 'X' }, mark: { 'ా': '>', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '\u2013', 'ౄ': '\u2014', 'ె': '\u00F0', 'ే': '\u00F3', 'ై': '\u00F0\u2022', 'ొ': '\u00F6', 'ో': 'Z', 'ౌ': 'o' } },
  'ఘ': { full: '\u0153\u00E8', base: '\u0153', vattu: '\u0192', pollu: '\u0160', padFor: { 'ఘ': '\u00FC', 'ష': '\u00FC' }, onFull: ['ా', 'ీ', 'ౄ'], mark: { 'ా': '\u00EB', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '\u2013', 'ౄ': '\u2014', 'ె': '\u00F0', 'ే': '\u00F4', 'ై': '\u00F0\u2022', 'ొ': '&', 'ో': '\u00F4\u00EA', 'ౌ': 'o' } },
  'ఙ': { full: '\u005C', base: '\u005C', vattu: ']', pollu: '\u0160', pad: '\u00FF', padFor: { 'క': '\u00FC', 'ఖ': '\u00FD', 'గ': '\u00FC', 'ఘ': '\u00FE', 'ఝ': '\u00FD', 'ఞ': '\u00FE', 'ట': '\u00FE', 'ఠ': '\u00FC', 'డ': '\u00FE', 'ఢ': '\u00FE', 'త': '\u00FC', 'థ': '\u00FE', 'ద': '\u00FE', 'ధ': '\u00FE', 'ర': '\u00FE', 'ష': '\u00FE', 'హ': '\u00FC', 'క్ష': '\u00FE' }, mark: { 'ా': '\u00EA', 'ి': '\u00EC', 'ీ': '\u00EF', 'ు': '$', 'ూ': '*', 'ృ': '#', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F4', 'ై': '\u00F1\u2022', 'ొ': '\u0178', 'ో': 'Z', 'ౌ': 'o' } },
  'చ': { full: '^\u00E6', base: '^', vattu: 'a', pollu: '\u0160', pad: '\u00FD', padFor: { 'క': '\u00FC', 'ఖ': '\u00FC', 'గ': '\u00FC', 'ఘ': '\u00FE', 'ఝ': '\u00FC', 'ఞ': '\u00FF', 'ట': '\u00FF', 'ఠ': '\u00FC', 'డ': '\u00FF', 'ఢ': '\u00FF', 'త': '\u00FC', 'థ': '\u00FF', 'ద': '\u00FF', 'ధ': '\u00FF', 'ర': '\u00FF', 'ల': '\u00FC', 'ష': '\u00FE', 'హ': '', 'క్ష': '\u00FF' }, onFull: ['ి', 'ూ', 'ౄ', 'ె', 'ే', 'ై'], pre: { 'ి': '_', 'ీ': '`' }, mark: { 'ా': '\u00E9', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '#', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F4', 'ై': '\u00F1\u2022', 'ొ': '\u0178', 'ో': 'Z', 'ౌ': 'o' } },
  'ఛ': { full: 'b\u00E6', base: 'b', vattu: 'e', pollu: '\u0160', pad: '\u00FD', padFor: { 'క': '\u00FC', 'ఖ': '\u00FC', 'గ': '\u00FC', 'ఘ': '\u00FE', 'ఝ': '\u00FC', 'ఞ': '\u00FF', 'ట': '\u00FF', 'ఠ': '\u00FC', 'డ': '\u00FF', 'ఢ': '\u00FF', 'త': '\u00FC', 'థ': '\u00FF', 'ద': '\u00FF', 'ధ': '\u00FF', 'ర': '\u00FF', 'ల': '\u00FC', 'ష': '\u00FE', 'హ': '', 'క్ష': '\u00FF' }, onFull: ['ి', 'ు', 'ూ', 'ౄ', 'ే'], pre: { 'ి': 'c', 'ీ': 'd' }, mark: { 'ా': '\u00E9', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '#', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F4', 'ై': '\u00F1\u2022', 'ొ': '\u0178', 'ో': 'Z', 'ౌ': 'o' } },
  'జ': { full: 'f', base: 'g', vattu: 'j', pollu: '\u0160', onFull: ['ి', 'ీ', 'ు', 'ృ', 'ౄ'], pre: { 'ి': 'h', 'ీ': 'i', 'ు': 'k', 'ూ': 'l' }, mark: { 'ా': '\u00EA', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '\u2013', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F4', 'ై': '\u00F1\u2022', 'ొ': '\u0178', 'ో': 'Z', 'ౌ': 'o' } },
  'ఝ': { full: 'm', base: 'm', vattu: '\u2030', pollu: '\u0160', mark: { 'ా': '\u00FB', 'ి': '\u00ED', 'ీ': '\u00EF', 'ు': '$', 'ూ': '*', 'ృ': '\u2013', 'ౄ': '\u2014', 'ె': '\u00F2', 'ే': '\u00F5', 'ై': '\u00F2\u2022', 'ొ': '\u00F7', 'ో': '\u00F9', 'ౌ': '\u00F1\u00FB' } },
  'ఞ': { full: 'p', base: 'p', vattu: 'q', pollu: '\u0160', pad: '\u00FC', padFor: { 'ఘ': '\u00FE', 'ష': '\u00FD', 'హ': '' }, mark: { 'ా': '\u00E9', 'ి': '\u00ED', 'ీ': '\u00EF', 'ు': '$', 'ూ': '*', 'ృ': '#', 'ౄ': '#*', 'ె': '\u00F2', 'ే': '\u00F5', 'ై': '\u00F2\u2022', 'ొ': '\u00F2\u0178', 'ో': '\u00F5Z', 'ౌ': 'o' } },
  'ట': { full: 'r', base: 's', vattu: 't', pollu: '\u0160', onFull: ['ు', 'ూ', 'ృ', 'ౄ'], mark: { 'ా': '>', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '\u2013', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F4', 'ై': '\u00F1\u2022', 'ొ': '\u0178', 'ో': 'Z', 'ౌ': 'o' } },
  'ఠ': { full: 'u\u00E6', base: 'u', vattu: 'x', pollu: '\u0160', pad: '\u00FF', padFor: { 'క': '\u00FC', 'ఖ': '\u00FD', 'గ': '\u00FC', 'ఘ': '\u00FE', 'ఝ': '\u00FC', 'ఞ': '\u00FE', 'ట': '\u00FE', 'ఠ': '\u00FC', 'డ': '\u00FE', 'ఢ': '\u00FE', 'త': '\u00FC', 'థ': '\u00FE', 'ద': '\u00FE', 'ధ': '\u00FE', 'ర': '\u00FE', 'ష': '\u00FE', 'హ': '\u00FC', 'క్ష': '\u00FE' }, onFull: ['ు', 'ూ', 'ౄ', 'ె', 'ే', 'ై'], pre: { 'ి': 'v', 'ీ': 'w' }, mark: { 'ా': '>', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '#', 'ౄ': '\u2014', 'ె': '\u00F0', 'ే': '\u00F3', 'ై': '\u00F0\u2022', 'ొ': '\u00F6', 'ో': '\u00F8', 'ౌ': 'o' } },
  'డ': { full: 'y\u00E6', base: 'y', vattu: 'z', pollu: '\u0160', pad: '\u00FD', padFor: { 'క': '\u00FC', 'ఖ': '\u00FC', 'గ': '\u00FC', 'ఘ': '\u00FE', 'ఝ': '\u00FC', 'ఞ': '\u00FF', 'ట': '\u00FF', 'ఠ': '\u00FC', 'డ': '\u00FF', 'ఢ': '\u00FF', 'త': '\u00FC', 'థ': '\u00FF', 'ద': '\u00FF', 'ధ': '\u00FF', 'ర': '\u00FF', 'ష': '\u00FE', 'హ': '', 'క్ష': '\u00FF' }, onFull: ['ు', 'ూ', 'ే'], mark: { 'ా': '>', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '#', 'ౄ': '#*', 'ె': '\u00F1', 'ే': '\u00F4', 'ై': '\u00F1\u2022', 'ొ': '\u0178', 'ో': '\u00F8', 'ౌ': 'o' } },
  'ఢ': { full: '\u00C9\u00E6', base: '\u00C9', vattu: '|', pollu: '\u0160', pad: '\u00FD', padFor: { 'క': '\u00FC', 'ఖ': '\u00FC', 'గ': '\u00FC', 'ఘ': '\u00FE', 'ఝ': '\u00FC', 'ఞ': '\u00FF', 'ట': '\u00FF', 'ఠ': '\u00FC', 'డ': '\u00FF', 'ఢ': '\u00FF', 'త': '\u00FC', 'థ': '\u00FF', 'ద': '\u00FF', 'ధ': '\u00FF', 'ర': '\u00FF', 'ష': '\u00FE', 'హ': '', 'క్ష': '\u00FF' }, onFull: ['ు', 'ూ', 'ే'], mark: { 'ా': '>', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '#', 'ౄ': '#*', 'ె': '\u00F1', 'ే': '\u00F4', 'ై': '\u00F1\u2022', 'ొ': '\u00F6', 'ో': '\u00F8', 'ౌ': 'o' } },
  'ణ': { full: '\u00D7', base: '\u00D7', vattu: '~', pollu: '\u0160', pad: '\u00FC', padFor: { 'ఘ': '\u00FE', 'ష': '\u00FF', 'హ': '' }, mark: { 'ా': '>', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '#', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F4', 'ై': '\u00F1\u2022', 'ొ': '\u0178', 'ో': 'Z', 'ౌ': 'o' } },
  'త': { full: '\u2122\u00E6', base: '\u2122', vattu: '\u00A2', pollu: '\u0160', pad: '\u00FD', padFor: { 'క': '\u00FC', 'ఖ': '\u00FC', 'గ': '\u00FC', 'ఘ': '\u00FE', 'ఝ': '\u00FC', 'ఞ': '\u00FF', 'ట': '\u00FF', 'ఠ': '\u00FC', 'డ': '\u00FF', 'ఢ': '\u00FF', 'త': '\u00FC', 'థ': '\u00FF', 'ద': '\u00FF', 'ధ': '\u00FF', 'ర': '\u00FF', 'ల': '\u00FC', 'ష': '\u00FE', 'హ': '', 'క్ష': '\u00FF' }, onFull: ['ూ', 'ే'], pre: { 'ి': '\u2020', 'ీ': '\u00A1' }, mark: { 'ా': '>', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '#', 'ౄ': '#*', 'ె': '\u00F1', 'ే': '\u00F4', 'ై': '\u00F1\u2022', 'ొ': '\u0178', 'ో': 'Z', 'ౌ': 'o' } },
  'థ': { full: '\u00A3\u00E6', base: '\u00A3', vattu: '\u00A6', pollu: '\u0160', pad: '\u00FD', padFor: { 'క': '\u00FC', 'ఖ': '\u00FC', 'గ': '\u00FC', 'ఘ': '\u00FE', 'ఝ': '\u00FC', 'ఞ': '\u00FF', 'ట': '\u00FF', 'ఠ': '\u00FC', 'డ': '\u00FE', 'ఢ': '\u00FE', 'త': '\u00FC', 'థ': '\u00FF', 'ద': '\u00FF', 'ధ': '\u00FF', 'ర': '\u00FF', 'ష': '\u00FE', 'హ': '', 'క్ష': '\u00FE' }, onFull: ['ూ', 'ౄ', 'ే'], pre: { 'ి': '\u00A4', 'ీ': '\u00A5' }, mark: { 'ా': '>', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '#', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F4', 'ై': '\u00F1\u2022', 'ొ': '\u00F2\u00FB', 'ో': '\u00F3o', 'ౌ': 'o' } },
  'ద': { full: '\u00A7\u00E6', base: '\u00A7', vattu: '\u00AA', pollu: '\u0160', pad: '\u00FD', padFor: { 'క': '\u00FC', 'ఖ': '\u00FC', 'గ': '\u00FC', 'ఘ': '\u00FE', 'ఝ': '\u00FC', 'ఞ': '\u00FF', 'ట': '\u00FF', 'ఠ': '\u00FC', 'డ': '\u00FE', 'ఢ': '\u00FE', 'త': '\u00FC', 'థ': '\u00FF', 'ద': '\u00FF', 'ధ': '\u00FF', 'ర': '\u00FF', 'ష': '\u00FE', 'హ': '', 'క్ష': '\u00FE' }, onFull: ['ూ', 'ౄ', 'ె', 'ే', 'ై', 'ౌ'], pre: { 'ి': '\u00A8', 'ీ': '\u00A9' }, mark: { 'ా': '>', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '#', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F3', 'ై': '\u00F1\u2022', 'ొ': '\u00F2\u00FB', 'ో': '\u00F8', 'ౌ': '\u00F1\u00FB' } },
  'ధ': { full: '\u00AB\u00A7\u00E6', base: '\u00AB\u00A7', vattu: '\u00AE', pollu: '\u0160', pad: '\u00FD', padFor: { 'క': '\u00FC', 'ఖ': '\u00FC', 'గ': '\u00FC', 'ఘ': '\u00FE', 'ఝ': '\u00FC', 'ఞ': '\u00FF', 'ట': '\u00FF', 'ఠ': '\u00FC', 'డ': '\u00FE', 'ఢ': '\u00FE', 'త': '\u00FC', 'థ': '\u00FF', 'ద': '\u00FF', 'ధ': '\u00FF', 'ర': '\u00FF', 'ష': '\u00FE', 'హ': '', 'క్ష': '\u00FE' }, onFull: ['ు', 'ూ', 'ౄ', 'ే'], mark: { 'ా': '>', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '#', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F4', 'ై': '\u00F1\u2022', 'ొ': '\u00F6', 'ో': '\u00F8', 'ౌ': 'o' } },
  'న': { full: '\u00AF\u00E8', base: '\u00AF', vattu: '\u00B2', pollu: '\u0160', pad: '\u00FF', padFor: { 'క': '\u00FC', 'ఖ': '\u00FD', 'గ': '\u00FC', 'ఘ': '\u00FE', 'ఝ': '\u00FC', 'ఞ': '\u00FE', 'ట': '\u00FE', 'ఠ': '\u00FC', 'డ': '\u00FE', 'ఢ': '\u00FE', 'త': '\u00FC', 'థ': '\u00FE', 'ద': '\u00FE', 'ధ': '\u00FE', 'ర': '\u00FE', 'ష': '\u00FE', 'హ': '', 'క్ష': '\u00FE' }, onFull: ['ి', 'ీ', 'ు', 'ూ', 'ృ', 'ౄ', 'ే'], pre: { 'ి': '\u00B0', 'ీ': '\u00B1' }, mark: { 'ా': '>', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '#', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F4', 'ై': '\u00F1\u2022', 'ొ': '\u0178', 'ో': 'Z', 'ౌ': 'o' } },
  'ప': { full: '\u00B3', base: '\u00B4', vattu: '\u00B5', pollu: '\u0160', padFor: { 'ఘ': '\u00FC' }, onFull: ['ౄ'], mark: { 'ా': '\u00FB', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '\u2013', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F4', 'ై': '\u00F1\u2022', 'ొ': '\u00F7', 'ో': '\u00F9', 'ౌ': '\u00F0\u00FB' } },
  'ఫ': { full: '\u00B8', base: '\u00B8', vattu: '\u00B9', pollu: '\u0160', padFor: { 'ఘ': '\u00FC', 'ష': '\u00FC' }, mark: { 'ా': '\u00EB', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '\u2013', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F4', 'ై': '\u00F1\u2022', 'ొ': '\u00F7', 'ో': '\u00F9', 'ౌ': '\u00F0\u00FB' } },
  'బ': { full: '\u00BA', base: '\u00BB', vattu: '\u00BE', pollu: '\u0160', onFull: ['ు', 'ూ', 'ృ', 'ౄ'], pre: { 'ి': '\u00BC', 'ీ': '\u00BD' }, mark: { 'ా': '\u00EA', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '\u2013', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F4', 'ై': '\u00F1\u2022', 'ొ': '\u0178', 'ో': 'Z', 'ౌ': 'o' } },
  'భ': { full: '\u00BF\u00E6', base: '\u00BF', vattu: '\u00C2', pollu: '\u0160', pad: '\u00FC', padFor: { 'ఘ': '\u00FE', 'ఞ': '\u00FD', 'ట': '\u00FD', 'డ': '\u00FD', 'ఢ': '\u00FD', 'థ': '\u00FD', 'ద': '\u00FD', 'ధ': '\u00FD', 'ర': '\u00FD', 'ష': '\u00FE', 'హ': '', 'క్ష': '\u00FD' }, onFull: ['ు', 'ూ', 'ౄ', 'ే'], pre: { 'ి': '\u00C0', 'ీ': '\u00C1' }, mark: { 'ా': '\u00EA', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '#', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F3', 'ై': '\u00F1\u2022', 'ొ': '\u0178', 'ో': 'Z', 'ౌ': 'o' } },
  'మ': { full: '\u02DC', base: '\u02DC', vattu: '\u00C3', pollu: '\u0160', mark: { 'ా': '>', 'ి': '\u00EC', 'ీ': '\u00EF', 'ు': '$', 'ూ': '*', 'ృ': '\u2013', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F3', 'ై': '\u00F1\u2022', 'ొ': '\u00F1\u00F7', 'ో': '\u00F3\u00EA', 'ౌ': 'o' } },
  'య': { full: '\u00C4\u00E7', base: '\u00C4', vattu: '\u00C5', pollu: '\u0160', pad: '\u00FC', padFor: { 'ఘ': '\u00FE', 'ష': '\u00FF', 'హ': '' }, onFull: ['ా', 'ి', 'ీ', 'ృ', 'ె', 'ే', 'ై', 'ొ', 'ో', 'ౌ'], mark: { 'ా': '\u00E9', 'ి': '\u00EC', 'ీ': '\u00EF', 'ు': '$', 'ూ': '*', 'ృ': '\u2013', 'ౄ': '#*', 'ె': '\u00F0', 'ే': '\u00F3', 'ై': '\u00F0\u2022', 'ొ': '\u00F2\u00E9', 'ో': '\u00F4\u00E9', 'ౌ': '\u00F2\u00FA' } },
  'ర': { full: '\u00C6\u00E6', base: '\u00C6', vattu: '\u00CA', pollu: '\u0160', pad: '\u00FF', padFor: { 'క': '\u00FC', 'ఖ': '\u00FD', 'గ': '\u00FC', 'ఘ': '\u00FE', 'ఝ': '\u00FC', 'ఞ': '\u00FE', 'ట': '\u00FE', 'ఠ': '\u00FC', 'డ': '\u00FE', 'ఢ': '\u00FE', 'త': '\u00FC', 'థ': '\u00FE', 'ద': '\u00FE', 'ధ': '\u00FE', 'ర': '\u00FE', 'ష': '\u00FE', 'హ': '\u00FC', 'క్ష': '\u00FE' }, onFull: ['ు', 'ూ', 'ౄ', 'ె', 'ే', 'ై'], pre: { 'ి': '\u00C7', 'ీ': '\u00C8' }, mark: { 'ా': '>', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '#', 'ౄ': '\u2014', 'ె': '\u00F0', 'ే': '\u00F3', 'ై': '\u00F0\u2022', 'ొ': '\u00F6', 'ో': '\u00F8', 'ౌ': 'o' } },
  'ఱ': { full: '\u201A', base: '\u201A', vattu: '[', pollu: '\u0160', pad: '\u00FC', padFor: { 'ఘ': '\u00FE', 'ష': '\u00FF', 'హ': '' }, mark: { 'ా': '>', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '#', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F4', 'ై': '\u00F1\u2022', 'ొ': '\u0178', 'ో': 'Z', 'ౌ': 'o' } },
  'ల': { full: '\u00CB', base: '\u00CC', vattu: '\u00CF', pollu: '\u0160', padFor: { 'ఘ': '\u00FC' }, onFull: ['ు', 'ూ', 'ృ', 'ౄ'], pre: { 'ి': '\u00CD', 'ీ': '\u00CE' }, mark: { 'ా': '>', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '\u2013', 'ౄ': '\u2014', 'ె': '\u00F0', 'ే': '\u00F3', 'ై': '\u00F0\u2022', 'ొ': '\u0178', 'ో': 'Z', 'ౌ': 'o' } },
  'ళ': { full: '\u00E2\u00E6', base: '\u00E2', vattu: '\u00E5', pollu: '\u0160', pad: '\u00FD', padFor: { 'క': '\u00FC', 'ఖ': '\u00FC', 'గ': '\u00FC', 'ఘ': '\u00FE', 'ఝ': '\u00FC', 'ఞ': '\u00FF', 'ట': '\u00FF', 'ఠ': '\u00FC', 'డ': '\u00FE', 'ఢ': '\u00FE', 'త': '\u00FC', 'థ': '\u00FF', 'ద': '\u00FF', 'ధ': '\u00FF', 'ర': '\u00FF', 'ష': '\u00FE', 'హ': '', 'క్ష': '\u00FE' }, onFull: ['ూ', 'ృ', 'ౄ', 'ె', 'ే', 'ై'], pre: { 'ి': '\u00E3', 'ీ': '\u00E4' }, mark: { 'ా': '\u00EA', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '\u2013', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F3', 'ై': '\u00F1\u2022', 'ొ': '\u0178', 'ో': 'Z', 'ౌ': 'o' } },
  'వ': { full: '\u00D0\u00E8', base: '\u00D0', vattu: '\u00D3', pollu: '\u0160', pad: '\u00FF', padFor: { 'క': '\u00FC', 'ఖ': '\u00FD', 'గ': '\u00FC', 'ఘ': '\u00FE', 'ఝ': '\u00FC', 'ఞ': '\u00FE', 'ట': '\u00FE', 'ఠ': '\u00FC', 'డ': '\u00FE', 'ఢ': '\u00FE', 'త': '\u00FC', 'థ': '\u00FE', 'ద': '\u00FE', 'ధ': '\u00FE', 'ర': '\u00FE', 'ష': '\u00FE', 'హ': '\u00FC', 'క్ష': '\u00FE' }, onFull: ['ి', 'ీ', 'ు', 'ూ', 'ృ', 'ౄ', 'ె', 'ై'], pre: { 'ి': '\u00D1', 'ీ': '\u00D2' }, mark: { 'ా': '>', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '\u2013', 'ౄ': '\u2014', 'ె': '\u00F0', 'ే': '\u00F4', 'ై': '\u00F0\u2022', 'ొ': '\u0178', 'ో': 'Z', 'ౌ': 'o' } },
  'శ': { full: '\u00D4\u00E6', base: '\u00D4', vattu: '\u00D8', pollu: '\u0160', pad: '\u00FF', padFor: { 'క': '\u00FC', 'గ': '\u00FD', 'ఘ': '\u00FE', 'ఝ': '\u00FD', 'ఞ': '\u00FE', 'ట': '\u00FE', 'ఠ': '\u00FC', 'డ': '\u00FE', 'ఢ': '\u00FE', 'త': '\u00FC', 'థ': '\u00FE', 'ద': '\u00FE', 'ధ': '\u00FE', 'ర': '\u00FE', 'ష': '\u00FE', 'హ': '\u00FC', 'క్ష': '\u00FE' }, onFull: ['ి', 'ు', 'ూ', 'ౄ', 'ె', 'ే', 'ై'], pre: { 'ి': '\u00D5', 'ీ': '\u00D6' }, mark: { 'ా': '>', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '\u2013', 'ౄ': '\u2014', 'ె': '\u00F0', 'ే': '\u00F3', 'ై': '\u00F0\u2022', 'ొ': '\u0178', 'ో': 'Z', 'ౌ': 'o' } },
  'ష': { full: '\u00D9', base: '\u00DA', vattu: '\u00DB', pollu: '\u0160', padFor: { 'ఘ': '\u00FC', 'ఞ': '\u00FC', 'ట': '\u00FC', 'డ': '\u00FC', 'ఢ': '\u00FC', 'థ': '\u00FC', 'ద': '\u00FC', 'ధ': '\u00FC', 'ర': '\u00FC', 'ష': '\u00FC', 'క్ష': '\u00FC' }, mark: { 'ా': '\u00FB', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '#', 'ౄ': '#*', 'ె': '\u00F0', 'ే': '\u00F4', 'ై': '\u00F0\u2022', 'ొ': '\u00F7', 'ో': '\u00F9', 'ౌ': '\u00F0\u00FB' } },
  'స': { full: '\u00DC', base: '\u00DD', vattu: '\u00DE', pollu: '\u0160', padFor: { 'ఘ': '\u00FC' }, onFull: ['ౄ'], mark: { 'ా': '\u00FB', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '\u2013', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F3', 'ై': '\u00F1\u2022', 'ొ': '\u00F7', 'ో': '\u00F9', 'ౌ': '\u00F0\u00FB' } },
  'హ': { full: '\u00E0', base: '\u00DF', vattu: '\u00E1', pollu: '\u0160', onFull: ['ు', 'ూ', 'ృ', 'ౄ'], mark: { 'ా': '\u00FB', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '\u2013', 'ౄ': '\u2014', 'ె': '\u00F1', 'ే': '\u00F3', 'ై': '\u00F1\u2022', 'ొ': '\u0178', 'ో': 'Z', 'ౌ': 'o' } },
  'క్ష': { full: '\u201E\u00E6', base: '\u201E', vattu: '<', pollu: '\u0160', pad: '\u00FE', padFor: { 'క': '\u00FF', 'గ': '\u00FF', 'ఘ': '\u203A', 'ఝ': '\u00FF', 'ఠ': '\u00FF', 'త': '\u00FF', 'హ': '\u00FC' }, onFull: ['ు', 'ూ', 'ౄ', 'ే', 'ొ'], mark: { 'ా': '>', 'ి': '\u00EC', 'ీ': '\u00EE', 'ు': '$', 'ూ': '*', 'ృ': '#', 'ౄ': '#*', 'ె': '\u00F1', 'ే': '\u00F3', 'ై': '\u00F1\u2022', 'ొ': '\u00F0o', 'ో': 'Z', 'ౌ': 'o' } },
};

/** Independent vowels. ఋ ౠ ఌ ౡ have no glyph; బ / ల plus kommus is the substitution
 *  the font's own users make, and it is emitted silently by request. */
export const INDEPENDENT_VOWELS: Record<string, string> = {
  'అ': 'A',
  'ఆ': 'B',
  'ఇ': 'C',
  'ఈ': 'D',
  'ఉ': 'E',
  'ఊ': 'F',
  'ఎ': 'G',
  'ఏ': 'H',
  'ఐ': 'I',
  'ఒ': 'J',
  'ఓ': 'K',
  'ఔ': 'L',
  'ఋ': '\u00BA$$',
  'ౠ': '\u00BA$*',
  'ఌ': '\u00CB$$',
  'ౡ': '\u00CB$*',
};

/** Fallback vowel-sign spelling, for a consonant with no per-pair entry. */
export const MATRAS: Record<string, string> = {
  'ా': '>',
  'ి': '\u00EC',
  'ీ': '\u00EE',
  'ు': '$',
  'ూ': '*',
  'ృ': '\u2013',
  'ౄ': '\u2014',
  'ె': '\u00F0',
  'ే': '\u00F3',
  'ై': '\u00F0\u2022',
  'ొ': '&',
  'ో': 'Z',
  'ౌ': 'o',
};

export const LIGATURES: Record<string, string> = {
  'శ్రీ': '}',
};

export const DIGITS: Record<string, string> = {
  '౦': '0',
  '౧': '1',
  '౨': '2',
  '౩': '3',
  '౪': '4',
  '౫': '5',
  '౬': '6',
  '౭': '7',
  '౮': '8',
  '౯': '9',
};
