// Mapping rules for Shree-Lipi Telugu Legacy Font Encoding
import type { MappingEntry } from './anu6';

export const SHREE_LIPI_UNICODE_TO_NONUNICODE: MappingEntry[] = [
  // Special Conjuncts
  { from: "క్షం", to: "õ´" },
  { from: "క్షా", to: "õ¾" },
  { from: "క్షి", to: "õ¿" },
  { from: "క్షీ", to: "õÀ" },
  { from: "క్ష", to: "õ" },
  { from: "జ్ఞ", to: "±" },
  { from: "త్ర", to: "º" },
  { from: "శ్రీ", to: "ÍÀ" },
  { from: "శ్ర", to: "Í" },

  // Base Vowels
  { from: "అ", to: "A" },
  { from: "ఆ", to: "B" },
  { from: "ఇ", to: "C" },
  { from: "ఈ", to: "D" },
  { from: "ఉ", to: "E" },
  { from: "ఊ", to: "F" },
  { from: "ఎ", to: "G" },
  { from: "ఏ", to: "H" },
  { from: "ఐ", to: "I" },
  { from: "ఒ", to: "J" },
  { from: "ఓ", to: "K" },
  { from: "ఔ", to: "L" },

  // Consonants
  { from: "క", to: "k" },
  { from: "ఖ", to: "K" },
  { from: "గ", to: "g" },
  { from: "ఘ", to: "G" },
  { from: "చ", to: "c" },
  { from: "ఛ", to: "C" },
  { from: "జ", to: "j" },
  { from: "ఝ", to: "J" },
  { from: "ట", to: "t" },
  { from: "ఠ", to: "T" },
  { from: "డ", to: "d" },
  { from: "ఢ", to: "D" },
  { from: "ణ", to: "N" },
  { from: "త", to: "w" },
  { from: "థ", to: "W" },
  { from: "ద", to: "x" },
  { from: "ధ", to: "X" },
  { from: "న", to: "n" },
  { from: "ప", to: "p" },
  { from: "ఫ", to: "P" },
  { from: "బ", to: "b" },
  { from: "భ", to: "B" },
  { from: "మ", to: "m" },
  { from: "య", to: "y" },
  { from: "ర", to: "r" },
  { from: "ల", to: "l" },
  { from: "వ", to: "v" },
  { from: "శ", to: "S" },
  { from: "ష", to: "R" },
  { from: "స", to: "s" },
  { from: "హ", to: "h" },
  { from: "ళ", to: "L" },

  // Matras
  { from: "ా", to: "¾" },
  { from: "ి", to: "¿" },
  { from: "ీ", to: "À" },
  { from: "ు", to: "Á" },
  { from: "ూ", to: "Â" },
  { from: "ె", to: "Ä" },
  { from: "ే", to: "Å" },
  { from: "ై", to: "Æ" },
  { from: "ొ", to: "Ç" },
  { from: "ో", to: "È" },
  { from: "ౌ", to: "É" },
  { from: "ం", to: "´" },
  { from: "ః", to: "µ" }
];
