#!/usr/bin/env python3
"""
Generate src/utils/mappings/shreeLipiTelugu0908.ts from the derived tables.

  python3 scratch/telugu0908/build_tables.py

Single source of truth: nothing in the TS file is hand-typed, so the forward and reverse
directions of the converter cannot drift apart. Inputs:

  heads.py            head / base / vattu / precomposed forms and the mark variant pool
  solved_cm.json      per-(consonant, vowel sign) spelling chosen by search.py stage `cm`

Fails loudly if two roles claim the same glyph slot or two Unicode keys would emit the same
string, which is how the earlier ad-hoc tables hid collisions such as ద and ధ sharing a base.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import heads as H
import slotinfo as SL

OUT = os.path.abspath(os.path.join(HERE, '..', '..', 'src', 'utils', 'mappings',
                                   'shreeLipiTelugu0908.ts'))
CM = os.path.join(HERE, 'solved_cm.json')
MATRAS = list('ాిీుూృౄెేైొోౌ')


def esc(cps):
    """codepoints -> a TS single-quoted literal, \\uXXXX for anything not plainly ASCII."""
    out = []
    for cp in cps:
        if 0x20 < cp < 0x7F and chr(cp) not in '\\\'"':
            out.append(chr(cp))
        else:
            out.append('\\u%04X' % cp)
    return "'" + ''.join(out) + "'"


def key(k):
    return "'" + k.replace('\\', '\\\\').replace("'", "\\'") + "'"


RAW = {}


def load_cm():
    """{consonant: {matra: [codepoints]}} from the search, falling back to the first width
    variant when the search has no verdict for a pair."""
    chosen = {}
    raw = json.load(open(CM)) if os.path.exists(CM) else {}
    RAW.update(raw)
    for c in H.HEAD:
        chosen[c] = {}
        for m in MATRAS:
            lab = raw.get(c + m, {}).get('label')
            chosen[c][m] = lab
    return chosen


def spell(c, m, lab):
    """Turn a search label back into the glyph sequence it stood for.

    Labels look like `003E`, `F0024` (leading F = the complete form rather than the narrow
    base, used by the signs that sit below the letter and so leave its top alone),
    `00F0.003C` (two pieces) or `pre` (a precomposed single glyph)."""
    if lab == 'pre':
        pre = H.PRECOMP_I.get(c)
        pu = H.PRECOMP_U.get(c)
        return {'ి': lambda: [pre[0]], 'ీ': lambda: [pre[1]],
                'ు': lambda: [pu[0]], 'ూ': lambda: [pu[1]]}[m]()
    full = lab.startswith('F')
    head = H.head(c) if full else H.head(c, with_matra=True)
    body = lab[1:] if full else lab
    return head + [int(piece, 16) for piece in body.split('.')]


def main():
    cm = load_cm()
    used, lines = {}, []

    def claim(cps, owner):
        for cp in cps if isinstance(cps, (list, tuple)) else [cps]:
            used.setdefault(cp, []).append(owner)

    P = lines.append
    P('''// GENERATED by scratch/telugu0908/build_tables.py - do not edit by hand.
//
// Encoding: Shree-Tel-0908 (Modular Infotech, 2001), addressed through the font's (3,1)
// Unicode cmap - the one both Chromium and Windows resolve text through. Every value below
// is a string of those cmap characters. The font's glyph names are standard Macintosh names
// assigned by position and carry no meaning, so nothing here was read off a name.
//
// The in-page preview needs the sanitised face (public/SHREE-TEL-web.ttf): Chromium's
// OpenType Sanitiser rejects the original outright ("post: Bad string index 5") and falls
// back to a Latin font without saying so.
//
// Provenance for every value: scratch/telugu0908/INVENTORY.md.''')
    P('')
    P('/** Free-standing marks. */')
    for name, cp in (('ANUSVARA', H.ANUSVARA), ('VISARGA', H.VISARGA), ('POLLU', H.POLLU),
                     ('NAKAARA_POLLU', H.NAKAARA_POLLU), ('REPH', H.REPH),
                     ('AI_LENGTH', H.AI_LENGTH), ('TA_RA', H.TA_RA)):
        P(f'export const {name} = {esc([cp])};')
        claim(cp, name)
    P('')
    P('''export interface ConsonantForms {
  /** Standalone letter, talakattu included where the letter takes one. */
  full: string;
  /** Form used when a vowel sign or a subscript follows; the sign takes the talakattu's place. */
  base: string;
  /** Subscript (vattu) form, emitted after a virama. */
  vattu: string;
  /** Single glyph covering base + vowel sign, where the font provides one. Cannot carry an
   *  intervening subscript, so it is used only when the cluster has none. */
  pre?: Record<string, string>;
  /** Per-consonant spelling of each vowel sign: which width variant, and whether the sign is
   *  written as one mark or two. Measured per pair - a single variant per sign is what made
   *  the earlier tables render ై ొ ో ౌ wrongly. */
  mark: Record<string, string>;
  /** Signs that follow `full` rather than `base`: the ones drawn below the letter, which
   *  leave its talakattu alone. */
  onFull?: string[];
  /** Advance-only glyph emitted between this letter and a following subscript. A subscript is
   *  a mark whose ink sits at about x -450..-60, so it needs the pen roughly 450 units in to
   *  land under the letter; a narrow letter plus its talakattu only reaches ~220 and the mark
   *  would be drawn beside it instead. Absent for letters already wide enough. */
  pad?: string;
  /** Which of the three width-matched pollu marks sits over this letter. */
  pollu: string;
  /** Subscripts whose own x range needs a different pad from this letter's default, keyed by
   *  the following consonant. The marks span x -599..-21, so one pad cannot centre all of
   *  them; an empty string means no pad at all. */
  padFor?: Record<string, string>;
}''')
    P('')
    P('export const CONSONANTS: Record<string, ConsonantForms> = {')
    for c in H.HEAD:
        full = H.head(c)
        base = H.head(c, with_matra=True)
        vattu = [H.VATTU[c]]
        claim(H.HEAD[c][0], f'{c}.head')
        if H.HEAD[c][2]:
            claim(H.HEAD[c][2], f'{c}.base')
        claim(vattu, f'{c}.vattu')
        pre, mark, onfull = {}, {}, []
        for m in MATRAS:
            lab = cm[c].get(m)
            if lab is None:
                lab = f"{H.MATRA_VARIANTS[m][0]:04X}" + ('+ai' if m == 'ై' else '')
            seq = spell(c, m, lab)
            if lab == 'pre':
                # A precomposed glyph is one unit and cannot carry a subscript between the
                # letter and the sign, so `mark` still needs a spelling for the cluster that
                # does: the search's best non-precomposed runner, else the generic variant.
                pre[m] = seq
                claim(seq, f'{c}.pre{m}')
                alt = next((l for l, _ in RAW.get(c + m, {}).get('runners', [])
                            if l != 'pre'), None)
                if alt:
                    lab = alt
                    seq = spell(c, m, alt)
                else:
                    mark[m] = [H.MATRA_VARIANTS[m][0]] + ([H.AI_LENGTH] if m == 'ై' else [])
                    continue
            # store the sign relative to the head the search chose, and remember which head
            head = full if lab.startswith('F') else base
            mark[m] = seq[len(head):]
            if lab.startswith('F'):
                onfull.append(m)
        # ౄ is ృ lengthened. Where the search picked the same glyph for both, the two would be
        # indistinguishable on the page and could not round-trip, so append the same lengthener
        # the font uses for ఋ -> ౠ.
        if mark.get('ౄ') == mark.get('ృ') and 'ృ' in mark:
            mark['ౄ'] = mark['ృ'] + [0x2A]
            if ('ృ' in onfull) != ('ౄ' in onfull):
                (onfull.append if 'ృ' in onfull else onfull.remove)('ౄ')

        # ై is the ె mark plus the hook under the letter - the way Noto spells its own ై, and
        # what the search picks for 24 of 36 letters. Normalising the remaining twelve to the
        # same spelling keeps one hook slot for one role: left free, the search borrows other
        # letters' subscripts as hooks, which then cannot be decoded back.
        if 'ె' in mark:
            mark['ై'] = mark['ె'] + [H.AI_LENGTH]
            if 'ె' in onfull and 'ై' not in onfull:
                onfull.append('ై')
            elif 'ె' not in onfull and 'ై' in onfull:
                onfull.remove('ై')

        for m, glyphs in mark.items():
            claim(glyphs, f'{c}.mark{m}')

        bits = [f'full: {esc(full)}', f'base: {esc(base)}', f'vattu: {esc(vattu)}',
                f'pollu: {esc([H.pollu_for(c, SL.SLOTS)])}']
        pad = H.conjunct_pad(c, SL.SLOTS)
        if pad:
            bits.append(f'pad: {esc([pad])}')
        over = {}
        for c2 in H.HEAD:
            want = H.pad_for(c, H.VATTU[c2], SL.SLOTS)
            if want is None and SL.SLOTS[H.VATTU[c2]]['class'] != 'below':
                continue
            if want != pad:
                over[c2] = [want] if want else []
        if over:
            bits.append('padFor: { '
                        + ', '.join(f'{key(k)}: {esc(v)}' for k, v in over.items()) + ' }')
        if onfull:
            bits.append('onFull: [' + ', '.join(key(m) for m in onfull) + ']')
        if pre:
            bits.append('pre: { ' + ', '.join(f'{key(m)}: {esc(v)}' for m, v in pre.items()) + ' }')
        bits.append('mark: { ' + ', '.join(f'{key(m)}: {esc(v)}' for m, v in mark.items()) + ' }')
        P(f'  {key(c)}: {{ {", ".join(bits)} }},')
    P('};')
    P('')
    P('/** Independent vowels. ఋ ౠ ఌ ౡ have no glyph; బ / ల plus kommus is the substitution')
    P(' *  the font\'s own users make, and it is emitted silently by request. */')
    P('export const INDEPENDENT_VOWELS: Record<string, string> = {')
    for k, v in H.VOWELS.items():
        P(f'  {key(k)}: {esc(v)},')
    P('};')
    P('')
    P('/** Fallback vowel-sign spelling, for a consonant with no per-pair entry. */')
    P('export const MATRAS: Record<string, string> = {')
    for m in MATRAS:
        v = H.MATRA_VARIANTS[m][0]
        P(f'  {key(m)}: {esc([v] + ([H.AI_LENGTH] if m == "ై" else []))},')
    P('};')
    P('')
    P('export const LIGATURES: Record<string, string> = {')
    for k, v in H.LIGATURES.items():
        P(f'  {key(k)}: {esc(v)},')
        claim(v, f'lig {k}')
    P('};')
    P('')
    P('export const DIGITS: Record<string, string> = {')
    for k, v in H.DIGITS.items():
        P(f'  {key(k)}: {esc(v)},')
    P('};')

    # A slot may legitimately be shared by many consonants in the same ROLE - every letter
    # that takes the same width variant of ా points at the same glyph. What must never happen
    # is one slot serving two different roles, which is how ్ఝ and ౌ both ended up on U+006F.
    bad = 0
    for cp, owners in sorted(used.items()):
        roles = {o.split('.', 1)[1] if '.' in o else o for o in owners}
        # the AI_LENGTH constant and every `markై` are the same role by construction
        if roles == {'AI_LENGTH', 'markై'}:
            continue
        if len(roles) < 2:
            continue
        # ద and ధ share a base; the pendant distinguishes them. head/base of one letter is
        # also fine (a letter with no narrow form uses its full form in both roles).
        letters = {o.split('.', 1)[0] for o in owners}
        if roles <= {'head', 'base'} and len(letters) <= 2:
            continue
        if roles <= {'vattu'} | {f'mark{m}' for m in MATRAS} and 'vattu' not in roles:
            continue
        print(f'  COLLISION U+{cp:04X}: {sorted(set(owners))}', file=sys.stderr)
        bad += 1
    if bad:
        print(f'  {bad} slot(s) serve more than one role', file=sys.stderr)

    with open(OUT, 'w') as fh:
        fh.write('\n'.join(lines) + '\n')
    print(f'{OUT}  ({len(H.HEAD)} consonants, {len(used)} slots claimed)')


if __name__ == '__main__':
    main()
