/**
 * Generate scratch/telugu0908/CHECKLIST.md and out/check.html.
 *
 *   node scratch/telugu0908/mkchecklist.mjs
 *
 * The checklist is ordered by how likely each row is to be WRONG - weakest evidence first -
 * so the first twenty minutes of someone's attention go where they are worth most. Every row
 * carries the exact legacy string the converter emits, so a row can be checked by pasting it
 * into anything that has Shree-Tel-0908 installed, not only in the HTML page.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { F } from './run.mjs';
import * as T from '../../src/utils/mappings/shreeLipiTelugu0908.ts';

const CONS = [...'కఖగఘఙచఛజఝఞటఠడఢణతథదధనపఫబభమయరఱలళవశషసహ', 'క్ష'];
const MAT = [...'ాిీుూృౄెేైొోౌ'];
const VOW = [...'అఆఇఈఉఊఎఏఐఒఓఔ'];

// stage-1 confidence, parsed out of heads.py so the two cannot drift
const heads = readFileSync('scratch/telugu0908/heads.py', 'utf8');
const conf = {};
for (const m of heads.matchAll(/^\s*'(\S+?)':\s*\(0x[0-9A-Fa-f]+,\s*(?:0x[0-9A-Fa-f]+|None),\s*(?:0x[0-9A-Fa-f]+|None),\s*([0-9.]+)\),/gm)) {
  conf[m[1]] = Number(m[2] ?? m[3]);
}
for (const m of heads.matchAll(/'(\S+?)':\s+\(0x[0-9A-Fa-f]{4},\s+(?:0x[0-9A-Fa-f]{4}|None),\s+(?:0x[0-9A-Fa-f]{4}|None),\s+([0-9.]+)\)/g)) {
  conf[m[1]] = Number(m[2]);
}

const geom = readFileSync('/tmp/geom.txt', 'utf8').trim().split('\n').filter(Boolean);

const esc = (s) => [...s].map((c) => {
  const n = c.codePointAt(0);
  return n > 0x20 && n < 0x7f ? c : `\\u${n.toString(16).toUpperCase().padStart(4, '0')}`;
}).join('');

const rows = [];
const push = (group, uni, note = '') =>
  rows.push({ group, uni, legacy: F(uni).text, note });

for (const c of CONS) push('consonant', c, conf[c] != null ? `evidence ${conf[c].toFixed(2)}` : '');
for (const v of VOW) push('vowel', v);
for (const v of [...'ఋౠఌౡ']) push('vowel', v, 'no glyph in the font - substituted on purpose');
for (const m of MAT) for (const c of ['క', 'త', 'మ', 'ప']) push(`sign ${m}`, c + m);
for (const g of geom) { const [a, b] = g.split(','); push('conjunct flagged', a + '్' + b, 'geometry says the subscript may sit off the letter'); }
for (const c of ['క', 'ర', 'న', 'మ', 'స']) push('pollu', c + '్');
for (const c of ['క', 'మ']) { push('sunna', c + 'ం'); push('visarga', c + 'ః'); }
push('ligature', 'శ్రీ');
push('digits', '౦౧౨౩౪౫౬౭౮౯');
for (const w of ['తెలుగు', 'ప్రాణము', 'లక్ష్మణుడు', 'విజ్ఞానము', 'అక్షరాలు', 'ధర్మము', 'సంస్కృతం'])
  push('word', w);

// ---- HTML: reference above, output below, in one row per item
const legacyB64 = readFileSync('public/SHREE-TEL-web.ttf').toString('base64');
const cells = rows.map((r, i) => `
  <tr id="r${i}"><td class="n">${i + 1}</td><td class="g">${r.group}</td>
  <td class="ref">${r.uni}</td><td class="out">${r.legacy.replace(/&/g, '&amp;').replace(/</g, '&lt;')}</td>
  <td class="code">${esc(r.legacy)}</td><td class="note">${r.note}</td>
  <td class="v"><label><input type=checkbox> ok</label></td></tr>`).join('');
writeFileSync('scratch/telugu0908/out/check.html', `<!doctype html><meta charset=utf-8>
<title>Shree-Tel-0908 check sheet</title><style>
@font-face{font-family:LEG;src:url(data:font/ttf;base64,${legacyB64}) format('truetype')}
body{font:14px system-ui;margin:24px;max-width:1100px}
table{border-collapse:collapse;width:100%}
td,th{border-bottom:1px solid #e5e5e5;padding:6px 10px;vertical-align:middle}
.n{color:#999;width:3em}.g{color:#666;white-space:nowrap;font-size:12px}
.ref{font-family:'Noto Serif Telugu',serif;font-size:30px}
.out{font-family:LEG;font-size:30px}
.code{font-family:ui-monospace,monospace;font-size:11px;color:#888}
.note{font-size:12px;color:#a00}
tr:hover{background:#fafafa}
h1{font-size:20px}p{color:#555}
</style>
<h1>Shree-Tel-0908 check sheet</h1>
<p><b>Reference</b> is Unicode Telugu in Noto Serif Telugu. <b>Output</b> is what the converter
emits, drawn in Shree-Tel-0908. They are different typefaces, so they will never look
identical - the question is only whether the output is the <i>same letter</i>.</p>
<table><tr><th></th><th>group</th><th>reference</th><th>output</th><th>legacy string</th><th></th><th></th></tr>
${cells}</table>`);

// ---- Markdown checklist
const md = [];
const weak = CONS.filter((c) => (conf[c] ?? 1) < 0.45);
md.push(`# Shree-Tel-0908 check sheet

Generated by \`node scratch/telugu0908/mkchecklist.mjs\`. ${rows.length} rows.

**How to use this.** Open \`scratch/telugu0908/out/check.html\` in a browser — it shows the
Unicode reference and the converter's output side by side for every row below, so you can
scan rather than read. Come back here to note what is wrong.

The two typefaces are different by design, so nothing will match pixel for pixel. The only
question per row is *is that the same letter*. Rows are ordered worst-evidence-first, so the
things most likely to be wrong are at the top of each section.

If a row is wrong, tell me the row number or the Telugu — the legacy string in the third
column tells me exactly which glyph slots to re-examine.

## Order to check in

1. **Consonants with weak evidence** (§1) — ${weak.length} letters rest on a measurement below
   0.45 and are the most likely thing in the whole table to be wrong.
2. **Flagged conjuncts** (§4) — 41 pairs where the geometry says the subscript may sit off the
   letter.
3. **Vowel signs** (§3) — the per-letter width variants. Wrong variant = sign in the wrong place.
4. Everything else.
`);

const bad = [...weak].sort((a, b) => (conf[a] ?? 1) - (conf[b] ?? 1));
md.push(`## 1. Consonants — weak evidence first

These ${weak.length} are where I would look first. The score is how well the chosen glyph matched a
shaped Unicode reference; correct pairs normally land at 0.55–0.75.

| letter | legacy | evidence | what to check |
|---|---|---|---|`);
for (const c of bad) md.push(`| ${c} | \`${esc(F(c).text)}\` | ${(conf[c] ?? 0).toFixed(2)} | is this the letter ${c} at all? |`);
md.push(`
The remaining ${CONS.length - weak.length} measured 0.48–0.73 and should be right:

| letter | legacy | evidence |
|---|---|---|`);
for (const c of CONS.filter((c) => (conf[c] ?? 1) >= 0.45)) md.push(`| ${c} | \`${esc(F(c).text)}\` | ${(conf[c] ?? 0).toFixed(2)} |`);

const table = (title, blurb, list) => {
  md.push(`\n## ${title}\n\n${blurb}\n`);
  md.push('| # | item | legacy | note |');
  md.push('|---|---|---|---|');
  for (const r of list) md.push(`| ${rows.indexOf(r) + 1} | ${r.uni} | \`${esc(r.legacy)}\` | ${r.note} |`);
};

table('2. Independent vowels',
  'Confirmed against your own reference output, so these should be exactly right. ఋ ౠ ఌ ౡ have no glyph in the font and are built from బ / ల plus kommus — you asked for that and for no warning, so they are expected to read as బు / బూ.',
  rows.filter((r) => r.group === 'vowel'));

for (const m of MAT) {
  table(`3.${MAT.indexOf(m) + 1} Vowel sign ${m}`,
    `Shown on four letters of different widths. The font ships up to three width variants of this sign and the converter picks one per letter, so a wrong pick shows up as the sign sitting too far left or right, not as the wrong sign.`,
    rows.filter((r) => r.group === `sign ${m}`));
}

table('4. Flagged conjuncts',
  'For these 41 pairs the geometry says the subscript may be drawn beside the letter rather than under it. Everything else in the 1296 pairs checks out geometrically, so if conjuncts look right here they very likely look right everywhere.',
  rows.filter((r) => r.group === 'conjunct flagged'));

table('5. Marks', 'Pollu (explicit virama), sunna and visarga. ర్ and న్ use dedicated single glyphs; the other letters take one of three width-matched pollu marks.',
  rows.filter((r) => ['pollu', 'sunna', 'visarga'].includes(r.group)));

table('6. Ligature and digits', 'శ్రీ is a single glyph in this font. Telugu digits map to the font\'s digit slots, which the atlas identified as Telugu rather than Latin shapes.',
  rows.filter((r) => ['ligature', 'digits'].includes(r.group)));

table('7. Whole words', 'The real test: running text with conjuncts, vowel signs and marks interacting.',
  rows.filter((r) => r.group === 'word'));

md.push(`
## Constants — every named value in the shipped table

Provenance for each is in \`INVENTORY.md\`. \`\\uXXXX\` is the (3,1) cmap codepoint the
converter emits, which is also the character you would type in a legacy app.

| constant | value | role | how it was identified |
|---|---|---|---|
| \`ANUSVARA\` | \`${esc(T.ANUSVARA)}\` | ం | your reference output (అం = A…); atlas 0.76 |
| \`VISARGA\` | \`${esc(T.VISARGA)}\` | ః | your reference output (అః = A@); atlas 0.86 |
| \`POLLU\` | \`${esc(T.POLLU)}\` | ్ default | atlas vs Noto \`viramatelu\` 0.74 |
| \`NAKAARA_POLLU\` | \`${esc(T.NAKAARA_POLLU)}\` | న్ as one glyph | atlas vs \`nakaarapollutelu\` 0.62 |
| \`REPH\` | \`${esc(T.REPH)}\` | ర్ as one glyph | atlas vs \`rephtelu\` 0.81 |
| \`AI_LENGTH\` | \`${esc(T.AI_LENGTH)}\` | the hook that turns ె into ై | atlas vs \`ailengthmarktelu\` 0.88 |
| \`TA_RA\` | \`${esc(T.TA_RA)}\` | త్ర as one glyph | atlas vs \`tarasubscripttelu\` 0.72 (not yet used) |

Talakattu hooks — the same mark at three x offsets, one per letter width:
\`\\u00E6\` centred, \`\\u00E7\` shifted right, \`\\u00E8\` shifted left. Twelve Telugu
consonants take none (ఖ ఙ జ ఝ ఞ ట ణ బ ఱ ల హ మ) and the measurements found that on their own.

Pad glyphs — five invisible slots used to push a subscript under its letter, advances 179, 200,
205, 242 and 404: \`\\u00FC\` \`\\u00FD\` \`\\u00FF\` \`\\u00FE\` \`\\u203A\`.

## Re-running the checks

\`\`\`
python3 scratch/telugu0908/build_tables.py          # regenerate tables, collision checks
python3 scratch/telugu0908/geomcheck.py             # subscript placement, no rendering
node    scratch/telugu0908/verify.mjs roundtrip     # forward/reverse consistency
node    scratch/telugu0908/verify.mjs spec > /tmp/spec.json
python3 scratch/telugu0908/bmatch.py /tmp/spec.json --paired
node    scratch/telugu0908/mkchecklist.mjs          # regenerate this file and check.html
npx vitest run src/utils/shreeLipiTelugu0908Converter.test.ts
\`\`\`
`);

writeFileSync('scratch/telugu0908/CHECKLIST.md', md.join('\n') + '\n');
console.log(rows.length + ' rows -> CHECKLIST.md and out/check.html');
