/**
 * Generate scratch/telugu0908/CHECK-TEXT.md and out/checktext.html - the full inventory in
 * reading order, for someone who reads Telugu to go through.
 *
 *   node scratch/telugu0908/mkchecktext.mjs
 *
 * Every row is "Unicode | what the converter emits". The legacy column can be copied straight
 * into anything that has Shree-Tel-0908 installed - Word, Photoshop, PageMaker - so the check
 * does not depend on the HTML page or on my rendering being right.
 */
import { writeFileSync, readFileSync } from 'node:fs';
import { F, R } from './run.mjs';

const VOW = [...'అఆఇఈఉఊఋౠఌౡఎఏఐఒఓఔ'];
const CONS = [...'కఖగఘఙచఛజఝఞటఠడఢణతథదధనపఫబభమయరఱలళవశషసహ', 'క్ష'];
const MAT = ['', ...'ాిీుూృౄెేైొోౌ'];
const PARAS = [
  ['Everyday prose',
   'తెలుగు భారతదేశంలోని ఆంధ్రప్రదేశ్, తెలంగాణ రాష్ట్రాలలో మాట్లాడబడే ఒక ప్రాచీన ద్రావిడ భాష. ఇది భారతదేశంలోని ఆరు ప్రాచీన భాషలలో ఒకటి.'],
  ['Conjunct-heavy',
   'శ్రీరాముడు లక్ష్మణుడితో కలిసి అగస్త్య మహర్షి ఆశ్రమానికి వెళ్లాడు. అక్కడ విజ్ఞానము, క్షమ, పరాక్రమము వంటి గుణాలను గురించి చర్చించారు.'],
  ['Sanskrit loanwords',
   'ప్రజ్ఞానము, శాస్త్రము, అస్త్రశస్త్రాలు, సంస్కృతం, ధర్మము, బ్రహ్మజ్ఞానం, తత్త్వశాస్త్రం, ఉత్కృష్టమైన.'],
  ['Every vowel sign on one letter',
   'క కా కి కీ కు కూ కృ కౄ కె కే కై కొ కో కౌ కం కః క్'],
  ['Doubled consonants',
   'అక్క అమ్మ అన్న ఇల్లు గొప్ప చెట్టు పిల్ల బొమ్మ మెట్టు కళ్ళు నిద్ర ఉత్తరం'],
  ['Numbers and punctuation',
   '౧౨౩ సంవత్సరం ౨౦౨౬. ధర: ౫౦౦ రూపాయలు; సరే, అలాగే!'],
  ['Marks',
   'సంఖ్య అంతం ఇంక పుంజం దుఃఖం అంతఃపురం'],
];

const esc = (s) => [...s].map((c) => {
  const n = c.codePointAt(0);
  return n > 0x20 && n < 0x7f ? c : `\\u${n.toString(16).toUpperCase().padStart(4, '0')}`;
}).join('');
const md = [];
const html = [];
let bad = 0;

const row = (uni) => {
  const out = F(uni);
  const back = R(out.text).text;
  const trip = back === uni ? '' : ` ⚠ decodes back as ${back}`;
  if (trip) bad += 1;
  return { uni, legacy: out.text, trip };
};

md.push(`# Shree-Lipi Telugu (Shree-Tel-0908) — full check text

Generated by \`node scratch/telugu0908/mkchecktext.mjs\`.

**How to check.** Two ways, and the second is the one that proves it:

1. Open \`scratch/telugu0908/out/checktext.html\` — reference and output side by side, no setup.
2. Copy any **legacy** cell below, paste it into Word or Photoshop, set the font to
   **Shree-Tel-0908**, and compare with the Unicode column. This is the real test: it uses the
   actual font on the actual machine, not my rendering of it.

The two typefaces are different by design, so nothing matches pixel for pixel. The only
question per row is *is that the same letter*. Anything marked ⚠ round-trips wrongly and is a
bug regardless of how it looks.

Tell me the row and I will fix it — the legacy string names the exact glyph slots involved.

---
`);

// vowels
md.push(`## 1. Vowels (16)\n\n| # | Unicode | legacy | codes | note |\n|---|---|---|---|---|`);
VOW.forEach((v, i) => {
  const r = row(v);
  const note = 'ఋౠఌౡ'.includes(v) ? 'no glyph in this font — built from బ / ల + kommus, by your instruction' : '';
  md.push(`| ${i + 1} | ${v} | \`${r.legacy}\` | \`${esc(r.legacy)}\` | ${note}${r.trip} |`);
});

// consonants
md.push(`\n## 2. Consonants (36)\n\nWith the talakattu where the letter takes one. Twelve Telugu consonants carry their own top and take none — the measurements found that on their own.\n\n| # | Unicode | legacy | codes | note |\n|---|---|---|---|---|`);
CONS.forEach((c, i) => {
  const r = row(c);
  md.push(`| ${i + 1} | ${c} | \`${r.legacy}\` | \`${esc(r.legacy)}\` | ${r.trip} |`);
});

// full gunintam per consonant
md.push(`\n## 3. Gunintālu — every consonant with every vowel sign\n\nThe font ships up to three width variants of each sign and the converter picks one per letter, so a wrong pick shows as the sign sitting too far left or right rather than as the wrong sign.\n`);
for (const c of CONS) {
  md.push(`\n**${c}** — ${MAT.map((m) => c + m).join('  ')}\n`);
  md.push(`| sign | Unicode | legacy | codes |`);
  md.push(`|---|---|---|---|`);
  for (const m of MAT) {
    const r = row(c + m);
    md.push(`| ${m || '(none)'} | ${c + m} | \`${r.legacy}\` | \`${esc(r.legacy)}\` |${r.trip}`);
  }
}

// conjuncts: every C + virama + C for a representative set of first letters, then the pairs
// geometry flagged
const FIRST = [...'కగతదనమరలవసప'];
md.push(`\n## 4. Conjuncts (vattulu)\n\nA subscript is a mark that draws back over whatever precedes it, so a narrow letter needs an invisible pad in front of the subscript or the mark lands beside the letter. That pad is why these work at all; if one looks wrong, the pad is the first suspect.\n`);
for (const a of FIRST) {
  md.push(`\n**${a}్ + …**\n`);
  md.push(`| Unicode | legacy | codes |`);
  md.push(`|---|---|---|`);
  for (const b of CONS) {
    const r = row(a + '్' + b);
    md.push(`| ${a}్${b} | \`${r.legacy}\` | \`${esc(r.legacy)}\` |${r.trip}`);
  }
}

md.push(`\n## 5. Marks, ligature, digits\n\n| Unicode | legacy | codes | what it is |\n|---|---|---|---|`);
const MARKS = [['కం', 'sunna'], ['కః', 'visarga'], ['క్', 'pollu (explicit virama)'],
  ['ర్', 'ర్ has a dedicated single glyph'], ['న్', 'న్ has a dedicated single glyph'],
  ['మ్', 'pollu on a wide letter'], ['శ్రీ', 'single ligature glyph'],
  ['క్ష', 'single glyph, not a conjunct'], ['క్ష్మ', 'two stacked subscripts'],
  ['౦౧౨౩౪౫౬౭౮౯', 'Telugu digits']];
for (const [u, what] of MARKS) {
  const r = row(u);
  md.push(`| ${u} | \`${r.legacy}\` | \`${esc(r.legacy)}\` | ${what}${r.trip} |`);
}

md.push(`\n## 6. Complex paragraphs\n\nThe real test: running text where conjuncts, vowel signs and marks interact. Each block gives the Unicode, then the legacy text to paste into Word or Photoshop with Shree-Tel-0908 selected.\n`);
for (const [title, text] of PARAS) {
  const out = F(text);
  const back = R(out.text).text;
  md.push(`\n### ${title}\n`);
  md.push(`**Unicode**\n\n> ${text}\n`);
  md.push(`**Legacy (paste this)**\n\n\`\`\`\n${out.text}\n\`\`\`\n`);
  const ok = back === text;
  md.push(`Round-trips back to the same Unicode: **${ok ? 'yes' : 'NO'}**` +
    (ok ? '.' : `\n\n> ${back}`));
  if (out.unmapped.length) md.push(`\nCharacters with no glyph in this font: ${out.unmapped.join(' ')}`);
  if (!ok) bad += 1;
}

md.push(`\n---\n\n${bad === 0 ? 'Every row above round-trips back to the same Unicode.' :
  `${bad} row(s) marked \u26a0 do not round-trip — those are bugs independent of how they look.`}\n`);

writeFileSync('scratch/telugu0908/CHECK-TEXT.md', md.join('\n') + '\n');

// ---- HTML twin
const b64 = readFileSync('public/SHREE-TEL-web.ttf').toString('base64');
const sec = [];
const tbl = (title, items) => {
  sec.push(`<h2>${title}</h2><table>`);
  for (const u of items) {
    const r = row(u);
    sec.push(`<tr><td class=ref>${u}</td><td class=out>${r.legacy.replace(/&/g, '&amp;').replace(/</g, '&lt;')}</td><td class=code>${esc(r.legacy)}</td><td class=w>${r.trip}</td></tr>`);
  }
  sec.push('</table>');
};
tbl('1. Vowels', VOW);
tbl('2. Consonants', CONS);
for (const c of CONS) tbl(`3. Gunintālu — ${c}`, MAT.map((m) => c + m));
for (const a of FIRST) tbl(`4. Conjuncts — ${a}్`, CONS.map((b) => a + '్' + b));
tbl('5. Marks, ligature, digits', MARKS.map(([u]) => u));
sec.push('<h2>6. Complex paragraphs</h2>');
for (const [title, text] of PARAS) {
  sec.push(`<h3>${title}</h3><p class=ref>${text}</p><p class=out>${F(text).text.replace(/&/g, '&amp;').replace(/</g, '&lt;')}</p>`);
}
writeFileSync('scratch/telugu0908/out/checktext.html', `<!doctype html><meta charset=utf-8>
<title>Shree-Tel-0908 full check</title><style>
@font-face{font-family:LEG;src:url(data:font/ttf;base64,${b64}) format('truetype')}
body{font:14px system-ui;margin:24px;max-width:1000px}
table{border-collapse:collapse;width:100%;margin-bottom:20px}
td{border-bottom:1px solid #eee;padding:5px 10px}
.ref{font-family:'Noto Serif Telugu',serif;font-size:28px;width:30%}
.out{font-family:LEG;font-size:28px;width:30%}
.code{font-family:ui-monospace,monospace;font-size:11px;color:#999}
.w{color:#c00;font-size:12px}
h2{font-size:16px;margin-top:28px;border-top:2px solid #333;padding-top:8px}
h3{font-size:14px;color:#555}
p.ref,p.out{font-size:24px;line-height:1.7;width:auto}
</style>
<h1>Shree-Tel-0908 — full check</h1>
<p>Top line of each pair is Unicode Telugu in Noto Serif Telugu; below it is the converter's
output in Shree-Tel-0908. Different typefaces, so judge whether it is the same <i>letter</i>.</p>
${sec.join('\n')}`);

console.log(`CHECK-TEXT.md + out/checktext.html written; ${bad} round-trip warning(s)`);
